# Generated by Django 5.0.14 on 2026-05-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=200)),
                ('vorname', models.CharField(max_length=80)),
                ('nachname', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=40)),
                ('mitarbeiter_anzahl', models.CharField(blank=True, choices=[('<50', 'unter 50'), ('50-120', '50–120'), ('121-250', '121–250'), ('251-500', '251–500'), ('>500', 'über 500')], max_length=10)),
                ('nachricht', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('bearbeitet', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Demo-Anfrage',
                'verbose_name_plural': 'Demo-Anfragen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
