# Generated by Django 5.0.14 on 2026-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_demorequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demorequest",
            options={
                "ordering": ("-erstellt_am",),
                "verbose_name": "Demo-Anfrage",
                "verbose_name_plural": "Demo-Anfragen",
            },
        ),
        migrations.AddField(
            model_name="tenant",
            name="encryption_key",
            field=models.BinaryField(
                default=b"",
                help_text="Fernet-Schlüssel für HinSchG-Meldungen (Sprint 5). Auto-generiert in save(). NIEMALS rotieren ohne Re-Encrypt-Migration — Datenverlust.",
            ),
        ),
    ]
