# Generated by Django 5.0.14 on 2026-05-17 10:25

import django.db.models.deletion
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_demorequest_options_tenant_encryption_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='Erste erfolgreiche Anmeldung des GF nach Self-Service-Onboarding.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_source',
            field=models.CharField(choices=[('manual', 'Manuell durch Vaeren-Admin'), ('self_service', 'Self-Service über vaeren.de/start'), ('pilot', 'Pilot-Vertrag')], default='manual', help_text='Wie ist der Tenant entstanden? Self-Service vs. manuell vs. Pilot.', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateField(blank=True, help_text='Trial-Tenants laufen nach 30 Tagen ab. Nach Ablauf wird Login geblockt, bis ein Pilot-/Bezahl-Plan zugewiesen wird. NULL = kein Trial.', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('trial', 'Trial (Self-Service)')], default='professional', max_length=20),
        ),
        migrations.CreateModel(
            name='OnboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_name', models.CharField(max_length=200)),
                ('schema_name', models.CharField(db_index=True, help_text='Gewünschter Subdomain-Teil (`<schema>.app.vaeren.de`).', max_length=63)),
                ('vorname', models.CharField(max_length=80)),
                ('nachname', models.CharField(max_length=80)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('telefon', models.CharField(blank=True, default='', max_length=40)),
                ('mitarbeiter_anzahl', models.CharField(blank=True, choices=[('<50', 'unter 50'), ('50-120', '50-120'), ('121-250', '121-250'), ('251-500', '251-500'), ('>500', 'über 500')], default='', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Eingereicht, Tenant-Bereitstellung läuft'), ('invitation_sent', 'Magic-Link-Mail versandt'), ('activated', 'GF hat Passwort gesetzt + eingeloggt'), ('failed', 'Bereitstellung fehlgeschlagen'), ('expired', 'Magic-Link 7d nicht eingelöst, Tenant pausiert')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('invite_token', models.CharField(default=tenants.models._generate_invite_token, editable=False, help_text='Magic-Link-Token, 32 Bytes URL-safe. Einlösbar 7 Tage.', max_length=64, unique=True)),
                ('invite_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_requests', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Onboarding-Anfrage',
                'verbose_name_plural': 'Onboarding-Anfragen',
                'ordering': ('-erstellt_am',),
            },
        ),
    ]
