# Generated by Django 5.0.14 on 2026-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_audit_signing_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='aktive_module',
            field=models.JSONField(blank=True, default=list, help_text='Liste aktiver Modul-Keys (core.modules.MODULE). Ersetzt schrittweise die Einzel-Flags.'),
        ),
    ]
