# Generated by Django 5.0.14 on 2026-05-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_llmcalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auftragsverarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rechtssitz_land', models.CharField(default='Deutschland', max_length=80)),
                ('rechtssitz_adresse', models.CharField(blank=True, default='', max_length=300)),
                ('kontakt_dsb', models.CharField(blank=True, default='', help_text='Name + Mail des Datenschutzbeauftragten des Anbieters.', max_length=200)),
                ('website', models.URLField(blank=True, default='')),
                ('drittland', models.CharField(choices=[('eu_ewr', 'EU/EWR'), ('angemessenheit', 'Drittland mit Angemessenheitsbeschluss'), ('scc', 'Drittland mit Standard-Vertragsklauseln (SCCs)'), ('bcr', 'Drittland mit Binding Corporate Rules (BCRs)'), ('kritisch', 'Drittland ohne SCC/BCR (kritisch — Art. 49?)')], default='eu_ewr', max_length=30)),
                ('status', models.CharField(choices=[('offen', 'Offen — Vertrag noch nicht abgeschlossen'), ('aktiv', 'Aktiv — AVV unterschrieben'), ('beendet', 'Beendet — Verarbeitung eingestellt'), ('pruefung', 'In Prüfung')], default='offen', max_length=20)),
                ('avv_abgeschlossen_am', models.DateField(blank=True, null=True)),
                ('avv_endet_am', models.DateField(blank=True, help_text='Befristete Verträge: Datum der Wieder-Erinnerung 30 Tage davor.', null=True)),
                ('avv_link', models.URLField(blank=True, default='', help_text='Link zum AVV-Dokument (DMS/Sharepoint).')),
                ('toms_link', models.URLField(blank=True, default='', help_text='Link zur TOMs-Dokumentation (technisch-organisatorische Maßnahmen).')),
                ('notizen', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auftragsverarbeiter',
                'verbose_name_plural': 'Auftragsverarbeiter',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AVVTask',
            fields=[
                ('compliancetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.compliancetask')),
                ('task_typ', models.CharField(choices=[('avv_abschliessen', 'AVV abschließen'), ('avv_verlaengern', 'AVV verlängern (Frist <30d)'), ('drittland_pruefen', 'Drittland-Status klären (SCC/BCR)'), ('toms_pruefen', 'TOMs-Dokumentation prüfen')], max_length=40)),
                ('verarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='auftragsverarbeitung.auftragsverarbeiter')),
            ],
            options={
                'verbose_name': 'AVV-Task',
                'verbose_name_plural': 'AVV-Tasks',
            },
            bases=('core.compliancetask',),
        ),
        migrations.CreateModel(
            name='Verarbeitungsschritt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zweck', models.TextField(help_text='Was wird wozu verarbeitet?')),
                ('datenkategorien', models.JSONField(blank=True, default=list, help_text="z. B. ['kontaktdaten','transaktionsdaten']")),
                ('betroffene_kategorien', models.JSONField(blank=True, default=list, help_text="z. B. ['kunden','interessenten','mitarbeitende']")),
                ('speicherdauer_monate', models.PositiveSmallIntegerField(blank=True, help_text='Wie lange werden die Daten beim Verarbeiter gespeichert?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schritte', to='auftragsverarbeitung.auftragsverarbeiter')),
            ],
            options={
                'verbose_name': 'Verarbeitungsschritt',
                'verbose_name_plural': 'Verarbeitungsschritte',
                'ordering': ['verarbeiter__name', 'zweck'],
            },
        ),
    ]
