# Generated by Django 5.0.14 on 2026-05-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflichtunterweisung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='fragen_pro_quiz',
            field=models.PositiveSmallIntegerField(default=10, help_text='Anzahl Fragen pro Quiz-Durchlauf, zufällig aus fragen-Pool gezogen und pro SchulungsTask persistiert. Muss <= fragen.count() sein.'),
        ),
        migrations.CreateModel(
            name='SchulungsTaskFrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reihenfolge', models.PositiveSmallIntegerField(default=0)),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pflichtunterweisung.frage')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frage_ziehungen', to='pflichtunterweisung.schulungstask')),
            ],
            options={
                'verbose_name': 'Gezogene Frage',
                'verbose_name_plural': 'Gezogene Fragen',
                'ordering': ('reihenfolge', 'id'),
                'unique_together': {('task', 'frage')},
            },
        ),
        migrations.AddField(
            model_name='schulungstask',
            name='gezogene_fragen',
            field=models.ManyToManyField(help_text='Beim ersten resolve gesampelt: kurs.fragen_pro_quiz Stück aus kurs.fragen.all(), persistiert pro Task, damit Mitarbeiter:innen bei Tab-Wechsel dieselben Fragen wiedersehen.', related_name='task_ziehungen', through='pflichtunterweisung.SchulungsTaskFrage', to='pflichtunterweisung.frage'),
        ),
    ]
