# Generated by Django 5.0.14 on 2026-05-16 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflichtunterweisung', '0002_pool_mechanik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='eigentuemer_tenant',
            field=models.CharField(blank=True, help_text='Schema-Name des Tenants, der den Kurs erstellt hat. Leer = Vaeren-Standardkatalog (read-only für Tenants).', max_length=63),
        ),
        migrations.AddField(
            model_name='kurs',
            name='erstellt_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_kurse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kurs',
            name='mindest_lesezeit_s',
            field=models.PositiveIntegerField(default=0, help_text="Sekunden pro Modul, ab denen 'Kenntnisnahme' aktivierbar ist. Nur ausgewertet bei quiz_modus=kenntnisnahme_lesezeit."),
        ),
        migrations.AddField(
            model_name='kurs',
            name='quiz_modus',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('kenntnisnahme', 'Kenntnisnahme'), ('kenntnisnahme_lesezeit', 'Kenntnisnahme + Min-Lesezeit')], default='quiz', help_text='Bestimmt, was der Mitarbeiter im Player macht.', max_length=30),
        ),
        migrations.AddField(
            model_name='kurs',
            name='zertifikat_aktiv',
            field=models.BooleanField(default=True, help_text='Wenn False, wird bei Abschluss kein PDF-Zertifikat generiert.'),
        ),
    ]
