# Generated by Django 5.0.14 on 2026-05-16 22:43

from django.db import migrations, models

# Mapping fuer die 20 Standard-Katalog-Kurse. Eigene Tenant-Kurse landen
# beim Backfill in 'sonstiges' und koennen ueber die UI re-kategorisiert
# werden.
STANDARD_KATALOG_KATEGORIEN = {
    # Arbeitsschutz
    "Arbeitsschutz — Grundunterweisung": "arbeitsschutz",
    "Persönliche Schutzausrüstung (PSA)": "arbeitsschutz",
    "Lärm und Vibration am Arbeitsplatz": "arbeitsschutz",
    "Flurförderzeuge & Gabelstapler": "arbeitsschutz",
    # Brand- & Erste Hilfe
    "Brandschutz am Arbeitsplatz": "brandschutz",
    "Erste Hilfe — Auffrischung": "brandschutz",
    # Gefahrstoffe & Maschinen
    "Umgang mit Gefahrstoffen": "gefahrstoffe",
    "Maschinen- und Anlagensicherheit": "gefahrstoffe",
    "Schweißen & Heißarbeiten": "gefahrstoffe",
    "Ladungssicherung": "gefahrstoffe",
    # Datenschutz & IT
    "DSGVO-Grundlagen": "datenschutz",
    "IT-Security & Phishing-Erkennung": "datenschutz",
    # Compliance & Recht
    "Antikorruption & Geschenke-Policy": "compliance",
    "AGG — Gleichbehandlung am Arbeitsplatz": "compliance",
    "Hinweisgeberschutz (HinSchG)": "compliance",
    "Lieferkettengesetz (LkSG)": "compliance",
    "Geldwäscheprävention (GwG)": "compliance",
    "Exportkontrolle & Sanktionen": "compliance",
    # Umwelt & Qualität
    "Umweltschutz & Abfallrecht": "umwelt",
    "ISO 9001 Qualitätsbewusstsein": "umwelt",
}


def backfill_kategorien(apps, schema_editor):
    """Setzt Kategorie fuer Standard-Katalog-Kurse anhand des Titels.

    Eigene Tenant-Kurse (eigentuemer_tenant != '') bleiben auf default
    'sonstiges' — der User kann sie ueber die UI re-kategorisieren.
    Idempotent: existierende Kategorien werden nicht ueberschrieben, falls
    der Kurs schon eine non-default-Kategorie hat (z.B. Re-Run).
    """
    Kurs = apps.get_model("pflichtunterweisung", "Kurs")
    for titel, kategorie in STANDARD_KATALOG_KATEGORIEN.items():
        Kurs.objects.filter(titel=titel, eigentuemer_tenant="", kategorie="sonstiges").update(
            kategorie=kategorie
        )


def noop_reverse(apps, schema_editor):
    """Reverse: setzt alle Kategorien auf default ('sonstiges').

    Die Operation ist destruktiv fuer eigene Kurse, aber die Migration
    rueckwaerts wird de facto nie aufgerufen — sie ist nur fuer Test-
    Rollback-Symmetrie da.
    """
    Kurs = apps.get_model("pflichtunterweisung", "Kurs")
    Kurs.objects.update(kategorie="sonstiges")


class Migration(migrations.Migration):

    dependencies = [
        ('pflichtunterweisung', '0003_kurs_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='kategorie',
            field=models.CharField(choices=[('arbeitsschutz', 'Arbeitsschutz'), ('brandschutz', 'Brand- & Erste Hilfe'), ('gefahrstoffe', 'Gefahrstoffe & Maschinen'), ('datenschutz', 'Datenschutz & IT'), ('compliance', 'Compliance & Recht'), ('umwelt', 'Umwelt & Qualität'), ('sonstiges', 'Sonstiges')], default='sonstiges', help_text='Thematische Einordnung fuer die Kurs-Bibliothek-Gruppierung.', max_length=30),
        ),
        migrations.RunPython(backfill_kategorien, reverse_code=noop_reverse),
    ]
