# Generated by Django 5.0.14 on 2026-05-16 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflichtunterweisung', '0004_kurs_kategorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kursmodul',
            name='transcript_cache',
            field=models.TextField(blank=True, help_text='Cache fuer YouTube-Untertitel oder Audio-Transkript (spaeter via youtube-transcript-api). Nur fuer LLM-Quiz.'),
        ),
        migrations.AddField(
            model_name='kursmodul',
            name='typ',
            field=models.CharField(choices=[('text', 'Text/Markdown'), ('pdf', 'PDF'), ('bild', 'Bild (PNG/JPG)'), ('office', 'Office (DOCX/PPTX)'), ('video_upload', 'Video-Upload'), ('video_youtube', 'YouTube-Embed')], default='text', help_text='Modul-Typ — bestimmt welches Inhalts-Feld gefuellt ist.', max_length=20),
        ),
        migrations.AddField(
            model_name='kursmodul',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube-Watch-URL. Befuellt nur bei typ=VIDEO_YOUTUBE.'),
        ),
        migrations.AlterField(
            model_name='kursmodul',
            name='inhalt_md',
            field=models.TextField(blank=True, help_text='Markdown-Lerninhalt. Befuellt nur bei typ=TEXT.'),
        ),
        migrations.CreateModel(
            name='KursAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_datei', models.FileField(upload_to='kurs-uploads/%Y/%m/')),
                ('original_mime', models.CharField(max_length=100)),
                ('original_size_bytes', models.PositiveBigIntegerField()),
                ('konvertierte_pdf', models.FileField(blank=True, help_text='Bei typ=office: LibreOffice-konvertierte PDF zur Browser-Anzeige.', null=True, upload_to='kurs-uploads/%Y/%m/')),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error')], default='clean', help_text="Im MVP immer 'clean'. Feld bleibt fuer Phase 2 (ClamAV).", max_length=20)),
                ('konvertierung_status', models.CharField(choices=[('not_needed', 'Nicht noetig'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Fehlgeschlagen')], default='not_needed', max_length=20)),
                ('compression_status', models.CharField(choices=[('not_needed', 'Nicht noetig'), ('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped (kein Gewinn)'), ('failed', 'Fehlgeschlagen')], default='not_needed', max_length=20)),
                ('compressed_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('extrahierter_text', models.TextField(blank=True, help_text='Plain-Text fuer LLM-Quiz-Generierung (Slice 3).')),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('hochgeladen_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hochgeladene_assets', to=settings.AUTH_USER_MODEL)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='pflichtunterweisung.kurs')),
            ],
            options={
                'verbose_name': 'Kurs-Asset',
                'verbose_name_plural': 'Kurs-Assets',
                'ordering': ('-hochgeladen_am',),
            },
        ),
        migrations.AddField(
            model_name='kursmodul',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Datei-Asset. Befuellt bei pdf/bild/office/video_upload.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='module', to='pflichtunterweisung.kursasset'),
        ),
    ]
