# Generated by Django 5.0.14 on 2026-05-17 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflichtunterweisung', '0005_modul_typ_und_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrageVorschlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('erklaerung', models.TextField(blank=True)),
                ('optionen', models.JSONField(help_text='Liste {text, ist_korrekt} — analog zu AntwortOption.')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('llm_modell', models.CharField(max_length=100)),
                ('llm_prompt_hash', models.CharField(help_text='SHA-256 des Prompts fuer Reproduzierbarkeit / Audit.', max_length=64)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('akzeptiert', 'Akzeptiert'), ('verworfen', 'Verworfen')], default='offen', max_length=20)),
                ('entschieden_am', models.DateTimeField(blank=True, null=True)),
                ('akzeptiert_als', models.ForeignKey(blank=True, help_text='Bei status=AKZEPTIERT: Verweis auf die erzeugte Frage.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pflichtunterweisung.frage')),
                ('entschieden_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entschiedene_vorschlaege', to=settings.AUTH_USER_MODEL)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_vorschlaege', to=settings.AUTH_USER_MODEL)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vorschlaege', to='pflichtunterweisung.kurs')),
                ('quell_module', models.ManyToManyField(blank=True, help_text='Aus welchen Modulen wurde dieser Vorschlag generiert?', related_name='basierte_vorschlaege', to='pflichtunterweisung.kursmodul')),
            ],
            options={
                'verbose_name': 'Fragen-Vorschlag',
                'verbose_name_plural': 'Fragen-Vorschlaege',
                'ordering': ('-erstellt_am',),
            },
        ),
    ]
