# Generated by Django 5.0.14 on 2026-05-17 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflichtunterweisung', '0006_fragenvorschlag'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.JSONField(help_text='Vollstaendige Struktur: kurs-felder, module (in Reihenfolge), fragen + optionen. Self-contained ausser Asset-Dateien.')),
                ('asset_pfad_map', models.JSONField(default=dict, help_text='{asset_id: snapshot_pfad} — Storage-Pfade der eingefrorenen Dateien.')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('welle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='pflichtunterweisung.schulungswelle')),
            ],
            options={
                'verbose_name': 'Welle-Snapshot',
                'verbose_name_plural': 'Welle-Snapshots',
            },
        ),
    ]
