# Generated by Django 5.0.14 on 2026-05-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflichtunterweisung', '0007_welle_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='schulungstask',
            name='gestartet_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
