# Generated by Django 5.0.14 on 2026-06-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pflichtunterweisung', '0008_task_gestartet_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='schulungstask',
            name='einladung_versendet_am',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt des erfolgreichen Einladungs-Mail-Versands. Ermöglicht Idempotenz beim asynchronen (Celery-)Versand: bereits versendete Tasks werden bei einem Retry übersprungen.', null=True),
        ),
    ]
