/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Liefert CSRF-Token + setzt csrftoken-Cookie.
         *
         *     Frontend ruft diesen Endpoint einmal beim App-Start, liest den Cookie
         *     aus und setzt für unsichere Methoden den `X-CSRFToken`-Header.
         */
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Login mit MFA-Bewusstsein.
         *
         *     Auth-Logik kommt vom `LoginSerializer` (validated_data["user"]). Wir
         *     haben dort den User; bevor `django_login` läuft, checken wir das
         *     `mfa_enabled`-Flag und unterbrechen den Flow falls nötig.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Calls Django logout method and delete the Token object
         *     assigned to the current User object.
         *
         *     Accepts/Returns nothing.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Zweite Stufe des MFA-Logins: ephemeraler Token + TOTP-Code → Session. */
        post: operations["auth_mfa_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/totp/setup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Erstellt einen TOTP-Secret + QR-URL für authentifizierten User.
         *
         *     Aktiviert MFA noch NICHT — das passiert erst nach erfolgreichem Verify.
         *     Secret wird in der Session zwischengelagert (allauth-Pattern).
         */
        post: operations["auth_mfa_totp_setup_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/totp/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Verifiziert TOTP-Code gegen Session-Secret + aktiviert MFA dauerhaft. */
        post: operations["auth_mfa_totp_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Calls Django Auth SetPasswordForm save method.
         *
         *     Accepts the following POST parameters: new_password1, new_password2
         *     Returns the success/fail message.
         */
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Calls Django Auth PasswordResetForm save method.
         *
         *     Accepts the following POST parameters: email
         *     Returns the success/fail message.
         */
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Password reset e-mail link is confirmed, therefore
         *     this resets the user's password.
         *
         *     Accepts the following POST parameters: token, uid,
         *         new_password1, new_password2
         *     Returns the success/fail message.
         */
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields.
         */
        get: operations["auth_user_retrieve"];
        /**
         * @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields.
         */
        put: operations["auth_user_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields.
         */
        patch: operations["auth_user_partial_update"];
        trace?: never;
    };
    "/api/compliance-tasks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API für ComplianceTask. CRUD kommt sprintweise pro Subtype. */
        get: operations["compliance_tasks_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compliance-tasks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API für ComplianceTask. CRUD kommt sprintweise pro Subtype. */
        get: operations["compliance_tasks_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compliance-tasks/overdue/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only API für ComplianceTask. CRUD kommt sprintweise pro Subtype. */
        get: operations["compliance_tasks_overdue_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness-Check inkl. aktivem Schema (verifiziert Tenant-Routing). */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mitarbeiter/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD für Mitarbeiter. */
        get: operations["mitarbeiter_list"];
        put?: never;
        /** @description CRUD für Mitarbeiter. */
        post: operations["mitarbeiter_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mitarbeiter/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD für Mitarbeiter. */
        get: operations["mitarbeiter_retrieve"];
        /** @description CRUD für Mitarbeiter. */
        put: operations["mitarbeiter_update"];
        post?: never;
        /** @description CRUD für Mitarbeiter. */
        delete: operations["mitarbeiter_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD für Mitarbeiter. */
        patch: operations["mitarbeiter_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ComplianceTask: {
            readonly id: number;
            /** @description Wert wird in Sprint 4+ relevant, wenn Subklassen existieren. */
            readonly polymorphic_ctype: string;
            readonly titel: string;
            /** @description Modul-Identifier (z. B. 'pflichtunterweisung', 'hinschg') */
            readonly modul: string;
            readonly kategorie: string;
            /** Format: date */
            readonly frist: string;
            readonly verantwortlicher: number | null;
            readonly betroffene: number[];
            readonly status: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        CsrfTokenResponse: {
            csrf_token: string;
        };
        HealthResponse: {
            status: string;
            schema: string;
        };
        Login: {
            username?: string;
            /** Format: email */
            email?: string;
            password: string;
        };
        MfaLoginRequest: {
            ephemeral_token: string;
            code: string;
        };
        Mitarbeiter: {
            readonly id: number;
            vorname: string;
            nachname: string;
            /** Format: email */
            email?: string;
            abteilung: string;
            /** @description Tätigkeit/Position */
            rolle: string;
            /** Format: date */
            eintritt: string;
            /** Format: date */
            austritt?: string | null;
            /** @description ERP-Sync-ID (Phase 2) */
            external_id?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PasswordChange: {
            new_password1: string;
            new_password2: string;
        };
        /** @description Serializer for requesting a password reset e-mail. */
        PasswordReset: {
            /** Format: email */
            email: string;
        };
        /** @description Serializer for confirming a password reset attempt. */
        PasswordResetConfirm: {
            new_password1: string;
            new_password2: string;
            uid: string;
            token: string;
        };
        PatchedMitarbeiter: {
            readonly id?: number;
            vorname?: string;
            nachname?: string;
            /** Format: email */
            email?: string;
            abteilung?: string;
            /** @description Tätigkeit/Position */
            rolle?: string;
            /** Format: date */
            eintritt?: string;
            /** Format: date */
            austritt?: string | null;
            /** @description ERP-Sync-ID (Phase 2) */
            external_id?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description User model w/o password */
        PatchedUserDetails: {
            /** ID */
            readonly pk?: number;
            /** Format: email */
            readonly email?: string;
            /** Vorname */
            first_name?: string;
            /** Nachname */
            last_name?: string;
        };
        RestAuthDetail: {
            readonly detail: string;
        };
        /**
         * @description * `offen` - Offen
         *     * `in_bearbeitung` - In Bearbeitung
         *     * `erledigt` - Erledigt
         *     * `ueberfaellig` - Überfällig
         * @enum {string}
         */
        StatusEnum: "offen" | "in_bearbeitung" | "erledigt" | "ueberfaellig";
        TotpSetupResponse: {
            secret: string;
            qr_url: string;
        };
        TotpVerifyRequest: {
            code: string;
        };
        /** @description User model w/o password */
        UserDetails: {
            /** ID */
            readonly pk: number;
            /** Format: email */
            readonly email: string;
            /** Vorname */
            first_name?: string;
            /** Nachname */
            last_name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfTokenResponse"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Login"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    auth_mfa_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaLoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MfaLoginRequest"];
                "multipart/form-data": components["schemas"]["MfaLoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaLoginRequest"];
                };
            };
        };
    };
    auth_mfa_totp_setup_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpSetupResponse"];
                "application/x-www-form-urlencoded": components["schemas"]["TotpSetupResponse"];
                "multipart/form-data": components["schemas"]["TotpSetupResponse"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpSetupResponse"];
                };
            };
        };
    };
    auth_mfa_totp_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TotpVerifyRequest"];
                "multipart/form-data": components["schemas"]["TotpVerifyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpVerifyRequest"];
                };
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
                "multipart/form-data": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordReset"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordReset"];
                "multipart/form-data": components["schemas"]["PasswordReset"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirm"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    auth_user_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetails"];
                };
            };
        };
    };
    auth_user_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserDetails"];
                "application/x-www-form-urlencoded": components["schemas"]["UserDetails"];
                "multipart/form-data": components["schemas"]["UserDetails"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetails"];
                };
            };
        };
    };
    auth_user_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserDetails"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserDetails"];
                "multipart/form-data": components["schemas"]["PatchedUserDetails"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetails"];
                };
            };
        };
    };
    compliance_tasks_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceTask"][];
                };
            };
        };
    };
    compliance_tasks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ein eindeutiger Ganzzahl-Wert, der compliance task identifiziert. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceTask"];
                };
            };
        };
    };
    compliance_tasks_overdue_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceTask"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    mitarbeiter_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mitarbeiter"][];
                };
            };
        };
    };
    mitarbeiter_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Mitarbeiter"];
                "application/x-www-form-urlencoded": components["schemas"]["Mitarbeiter"];
                "multipart/form-data": components["schemas"]["Mitarbeiter"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mitarbeiter"];
                };
            };
        };
    };
    mitarbeiter_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ein eindeutiger Ganzzahl-Wert, der mitarbeiter identifiziert. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mitarbeiter"];
                };
            };
        };
    };
    mitarbeiter_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ein eindeutiger Ganzzahl-Wert, der mitarbeiter identifiziert. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Mitarbeiter"];
                "application/x-www-form-urlencoded": components["schemas"]["Mitarbeiter"];
                "multipart/form-data": components["schemas"]["Mitarbeiter"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mitarbeiter"];
                };
            };
        };
    };
    mitarbeiter_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ein eindeutiger Ganzzahl-Wert, der mitarbeiter identifiziert. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mitarbeiter_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ein eindeutiger Ganzzahl-Wert, der mitarbeiter identifiziert. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMitarbeiter"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMitarbeiter"];
                "multipart/form-data": components["schemas"]["PatchedMitarbeiter"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mitarbeiter"];
                };
            };
        };
    };
}
