# Generated by Django 5.0.14 on 2026-05-17 10:52

import core.fields
import datenpannen.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datenpanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('art', models.CharField(choices=[('verlust_geraet', 'Verlust/Diebstahl Endgerät'), ('phishing', 'Phishing/Social-Engineering'), ('ransomware', 'Ransomware/Malware'), ('fehlversand', 'Fehlversand (E-Mail/Brief)'), ('unberechtigter_zugriff', 'Unberechtigter Zugriff'), ('konfigurationsfehler', 'Konfigurations- oder Berechtigungs-Fehler'), ('systemausfall', 'Systemausfall mit Daten-Auswirkung'), ('insider', 'Insider-Vorfall (vorsätzlich)'), ('sonstiges', 'Sonstiges')], max_length=40)),
                ('beschreibung_verschluesselt', core.fields.EncryptedTextField(help_text='Was ist passiert? Verschlüsselt at-rest.')),
                ('entdeckt_am', models.DateTimeField(help_text='Wann wurde die Panne entdeckt? Startet die 72-h-Frist Art. 33.')),
                ('vorfall_zeitraum_von', models.DateTimeField(blank=True, help_text='Wann begann der Vorfall (falls bekannt)?', null=True)),
                ('vorfall_zeitraum_bis', models.DateTimeField(blank=True, null=True)),
                ('entdeckt_durch', models.CharField(blank=True, default='', help_text='Name oder Rolle der entdeckenden Person.', max_length=200)),
                ('risiko', models.CharField(blank=True, choices=[('kein_risiko', 'Kein Risiko'), ('gering', 'Geringes Risiko'), ('hoch', 'Hohes Risiko')], default='', help_text='Bewertung NACH menschlicher Prüfung. LLM-Vorschlag liegt in risiko_vorschlag — DARF NICHT automatisch übernommen werden.', max_length=20)),
                ('risiko_vorschlag', models.CharField(blank=True, choices=[('kein_risiko', 'Kein Risiko'), ('gering', 'Geringes Risiko'), ('hoch', 'Hohes Risiko')], default='', help_text='LLM-Vorschlag (RDG-Layer-2 validiert). Nur Vorschlag.', max_length=20)),
                ('risiko_begruendung_verschluesselt', core.fields.EncryptedTextField(blank=True, default='', help_text='Begründung der finalen Einstufung.')),
                ('anzahl_betroffene_geschaetzt', models.PositiveIntegerField(blank=True, help_text='Geschätzte Anzahl betroffener Personen. NULL = noch unklar.', null=True)),
                ('datenkategorien', models.JSONField(blank=True, default=list, help_text="Liste DSGVO-Datenkategorien, z. B. ['kontaktdaten','gesundheitsdaten','sozialversicherung'].")),
                ('status', models.CharField(choices=[('entdeckt', 'Entdeckt — Klassifizierung läuft'), ('bewertet', 'Bewertet — Maßnahmen geplant'), ('gemeldet', 'Aufsichtsbehörde informiert'), ('abgeschlossen', 'Abgeschlossen'), ('nicht_meldepflichtig', 'Dokumentiert, nicht meldepflichtig')], default='entdeckt', max_length=30)),
                ('frist_meldung_behoerde', models.DateTimeField(default=datenpannen.models._frist_meldung_behoerde, help_text='72 Stunden nach entdeckt_am. Auto-gesetzt bei Anlage.')),
                ('behoerde_gemeldet_am', models.DateTimeField(blank=True, null=True)),
                ('behoerde_aktenzeichen', models.CharField(blank=True, default='', help_text='Aktenzeichen der Aufsichtsbehörde nach Meldung.', max_length=80)),
                ('frist_benachrichtigung_betroffene', models.DateField(default=datenpannen.models._frist_benachrichtigung_betroffene)),
                ('betroffene_benachrichtigt_am', models.DateTimeField(blank=True, null=True)),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verantwortlicher_user', models.ForeignKey(blank=True, help_text='Wer kümmert sich operativ um die Bearbeitung?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datenpannen_verantwortlich', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datenpanne',
                'verbose_name_plural': 'Datenpannen',
                'ordering': ['-entdeckt_am'],
            },
        ),
        migrations.CreateModel(
            name='DatenpannenTask',
            fields=[
                ('compliancetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.compliancetask')),
                ('task_typ', models.CharField(choices=[('meldung_behoerde', 'Meldung an Aufsichtsbehörde (72h)'), ('benachrichtigung_betroffene', 'Benachrichtigung Betroffener'), ('abschlussdoku', 'Abschluss-Dokumentation')], max_length=40)),
                ('datenpanne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='datenpannen.datenpanne')),
            ],
            options={
                'verbose_name': 'Datenpannen-Task',
                'verbose_name_plural': 'Datenpannen-Tasks',
            },
            bases=('core.compliancetask',),
        ),
        migrations.CreateModel(
            name='Massnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('sofort', 'Sofortmaßnahme (Schadensbegrenzung)'), ('dauerhaft', 'Dauerhafte Maßnahme (Prävention)'), ('kommunikation', 'Kommunikation (intern/extern)')], max_length=20)),
                ('beschreibung', models.TextField()),
                ('geplant_bis', models.DateField(blank=True, null=True)),
                ('erledigt_am', models.DateTimeField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('datenpanne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massnahmen', to='datenpannen.datenpanne')),
                ('verantwortlich', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datenpannen_massnahmen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maßnahme',
                'verbose_name_plural': 'Maßnahmen',
                'ordering': ['typ', 'geplant_bis'],
            },
        ),
        migrations.AddIndex(
            model_name='datenpanne',
            index=models.Index(fields=['status', '-entdeckt_am'], name='datenpannen_status_e42fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='datenpanne',
            index=models.Index(fields=['risiko'], name='datenpannen_risiko_08a6c2_idx'),
        ),
    ]
