# Generated by Django 5.0.14 on 2026-05-17 16:07

import auditor_export.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditExportCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('titel', models.CharField(max_length=200)),
                ('norm', models.CharField(choices=[('iso_27001', 'ISO/IEC 27001'), ('iso_42001', 'ISO/IEC 42001 (KI-Managementsystem)'), ('nis2', 'NIS2-Richtlinie'), ('dsgvo', 'DSGVO'), ('ai_act', 'EU AI Act'), ('arbeitsschutz', 'Arbeitsschutz (DGUV)'), ('pflichtunterweisung', 'Pflichtunterweisungen'), ('hinschg', 'Hinweisgeberschutzgesetz'), ('avv', 'Auftragsverarbeitungs-Verträge'), ('datenpannen', 'Datenpannen (Art. 33 DSGVO)'), ('transparenzregister', 'Transparenzregister (GwG)')], max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('controls_json', models.JSONField(default=list)),
                ('geladen_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit-Export-Catalog',
                'verbose_name_plural': 'Audit-Export-Catalogs',
                'ordering': ['norm', 'version'],
            },
        ),
        migrations.CreateModel(
            name='AuditExportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template', models.CharField(choices=[('iso_27001_audit', 'ISO-27001 Annex-A Audit'), ('gap_analyse', 'GAP-Analyse (Lücken rot markiert)'), ('tisax_light', 'TISAX-Light (Automotive-Zulieferer)'), ('ai_act_konformitaet', 'AI-Act Konformitätsbericht'), ('nis2_behoerden_vorlage', 'NIS2 Behörden-Vorlage (BSI)'), ('bfdi_template', 'BfDI/LDA Datenschutz-Anfrage'), ('geschaeftsfuehrer_mappe', 'GF-Mappe (kurz, Executive Summary)')], default='iso_27001_audit', help_text='Audit-Template aus AUDIT_TEMPLATES-Registry', max_length=50)),
                ('norm_scope', models.JSONField(default=list, help_text='Liste von NormScope-Strings, M:N als JSON-Array')),
                ('zeitraum_von', models.DateField()),
                ('zeitraum_bis', models.DateField()),
                ('filter_json', models.JSONField(blank=True, default=dict, help_text="Pro Modul Sub-Filter, z. B. {'hinschg': {'status': ['neu']}}")),
                ('evidence_mode', models.CharField(choices=[('embed', 'Originalfiles im ZIP einbetten'), ('reference', 'Nur Hash-Referenzen (kleinere Bundle-Größe)')], default='embed', max_length=20)),
                ('anonymisieren_pii', models.BooleanField(default=False, help_text='Wenn True: Mitarbeiter-Namen werden zu MA-001/MA-002 maskiert.')),
                ('watermark_draft', models.BooleanField(default=False, help_text='DRAFT-Wasserzeichen im PDF')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_export_profiles_erstellt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit-Export-Profil',
                'verbose_name_plural': 'Audit-Export-Profile',
                'ordering': ['-aktualisiert_am'],
            },
        ),
        migrations.CreateModel(
            name='AuditExportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Eingereiht'), ('running', 'Läuft'), ('done', 'Fertig'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='queued', max_length=20)),
                ('result_path', models.CharField(blank=True, default='', max_length=512)),
                ('zip_path', models.CharField(blank=True, default='', max_length=512)),
                ('pdf_path', models.CharField(blank=True, default='', max_length=512)),
                ('oscal_ssp_path', models.CharField(blank=True, default='', max_length=512)),
                ('oscal_assessment_path', models.CharField(blank=True, default='', max_length=512)),
                ('file_hash_sha256', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 des fertigen ZIP-Bundles.', max_length=64)),
                ('pdf_hash_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('generation_log', models.JSONField(default=list, help_text='Liste von {ts, level, aggregator, message}-Einträgen')),
                ('error', models.TextField(blank=True, default='')),
                ('mappe_id', models.CharField(default=auditor_export.models._generate_mappe_id, editable=False, help_text='Menschen-lesbare Run-ID, Format VAE-YYYY-MMDD-XXXX', max_length=30, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='auditor_export.auditexportprofile')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_export_runs_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit-Export-Lauf',
                'verbose_name_plural': 'Audit-Export-Läufe',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='auditor_exp_status_08b106_idx'), models.Index(fields=['mappe_id'], name='auditor_exp_mappe_i_6962d2_idx')],
            },
        ),
    ]
