# Generated by Django 5.0.14 on 2026-05-30 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('seite', models.PositiveIntegerField(default=1)),
                ('nummer', models.CharField(blank=True, max_length=40)),
                ('text', models.TextField()),
                ('feld_referenz', models.JSONField(blank=True, default=dict)),
                ('kategorie', models.CharField(blank=True, max_length=120)),
                ('extraktion_quelle', models.CharField(default='struktur', max_length=20)),
            ],
            options={
                'ordering': ['reihenfolge'],
            },
        ),
        migrations.CreateModel(
            name='Antwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entwurf_text', models.TextField(blank=True, default='')),
                ('bestaetigt_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('editiert', 'Editiert'), ('leer', 'Leer/offen')], default='entwurf', max_length=12)),
                ('confidence', models.FloatField(default=0.0)),
                ('platzierung_confidence', models.FloatField(blank=True, null=True)),
                ('bestaetigt_at', models.DateTimeField(blank=True, null=True)),
                ('bestaetigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bestaetigte_antworten', to=settings.AUTH_USER_MODEL)),
                ('frage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antwort', to='fragebogen.frage')),
            ],
        ),
        migrations.CreateModel(
            name='AntwortBibliothekEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage_kanonisch', models.TextField()),
                ('antwort_text', models.TextField()),
                ('quelle_referenzen', models.JSONField(blank=True, default=list)),
                ('kategorie', models.CharField(blank=True, max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('verwendungs_count', models.PositiveIntegerField(default=0)),
                ('zuletzt_verwendet', models.DateTimeField(blank=True, null=True)),
                ('erstellt_at', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_at', models.DateTimeField(auto_now=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bibliothek_eintraege', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AntwortQuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quelle_typ', models.CharField(max_length=40)),
                ('referenz', models.CharField(blank=True, max_length=255)),
                ('auszug', models.TextField(blank=True, default='')),
                ('antwort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quellen', to='fragebogen.antwort')),
            ],
        ),
        migrations.CreateModel(
            name='Fragebogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_datei', models.FileField(blank=True, upload_to='fragebogen/%Y/%m/')),
                ('dateiname', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=30)),
                ('tier', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('hochgeladen', 'Hochgeladen'), ('analysiert', 'Analysiert'), ('vorgeschlagen', 'Vorschläge erstellt'), ('in_review', 'In Prüfung'), ('exportiert', 'Exportiert'), ('fehler', 'Fehler')], default='hochgeladen', max_length=20)),
                ('quelle_oem', models.CharField(blank=True, max_length=255)),
                ('export_datei', models.FileField(blank=True, upload_to='fragebogen-export/%Y/%m/')),
                ('tier2_job_status', models.CharField(blank=True, default='', max_length=20)),
                ('bestaetigte_seiten', models.JSONField(blank=True, default=list)),
                ('final_attestiert_at', models.DateTimeField(blank=True, null=True)),
                ('erstellt_at', models.DateTimeField(auto_now_add=True)),
                ('final_attestiert_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fragebogen_attestierungen', to=settings.AUTH_USER_MODEL)),
                ('hochgeladen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fragebogen_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='frage',
            name='fragebogen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragen', to='fragebogen.fragebogen'),
        ),
    ]
