# Generated by Django 5.0.14 on 2026-05-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragebogen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antwort',
            name='rdg_ok',
            field=models.BooleanField(default=True),
        ),
    ]
