# Generated by Django 5.0.14 on 2026-05-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('system', 'IT-System / Server'), ('app', 'Anwendung / SaaS'), ('netz', 'Netzwerk-Segment'), ('daten', 'Daten-Sammlung'), ('hardware', 'Endgerät / Hardware'), ('drittanbieter', 'Drittanbieter-Dienst')], max_length=30)),
                ('beschreibung', models.TextField(blank=True, default='')),
                ('eigentuemer', models.CharField(blank=True, default='', help_text='Person oder Team, das das Asset verantwortet.', max_length=200)),
                ('kritikalitaet', models.CharField(choices=[('niedrig', 'Niedrig'), ('mittel', 'Mittel'), ('hoch', 'Hoch (Geschäfts-kritisch)')], default='mittel', max_length=20)),
                ('schutzziele', models.JSONField(blank=True, default=list, help_text="z. B. ['vertraulichkeit','integritaet','verfuegbarkeit']")),
                ('standort', models.CharField(blank=True, default='', max_length=200)),
                ('externe_drittanbieter', models.CharField(blank=True, default='', help_text='Wenn Asset bei einem Drittanbieter läuft, hier benennen.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['typ', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BetroffenheitsCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitarbeiter_anzahl', models.PositiveIntegerField(blank=True, null=True)),
                ('jahresumsatz_eur', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sektor', models.CharField(blank=True, choices=[('energie', 'Energie'), ('verkehr', 'Verkehr'), ('bank', 'Banken/Finanzmarkt'), ('gesundheit', 'Gesundheit'), ('trinkwasser', 'Trinkwasser'), ('abwasser', 'Abwasser'), ('digital_infra', 'Digitale Infrastruktur'), ('oeff_verw', 'Öffentliche Verwaltung'), ('raumfahrt', 'Raumfahrt'), ('post_kurier', 'Post & Kurier'), ('abfall', 'Abfallwirtschaft'), ('chemie', 'Chemie'), ('lebensmittel', 'Lebensmittel'), ('industrie', 'Verarbeitendes Gewerbe (Anhang II)'), ('digital_dienste', 'Digitale Dienste'), ('forschung', 'Forschung'), ('sonstiges', 'Sonstiges')], default='', max_length=30)),
                ('erbringt_kritische_dienstleistung', models.BooleanField(default=False)),
                ('klassifizierung', models.CharField(choices=[('nicht_betroffen', 'Nicht NIS2-pflichtig'), ('unklar', 'Unklar — weitere Prüfung nötig'), ('wichtig', 'Wichtige Einrichtung'), ('wesentlich', 'Wesentliche Einrichtung')], default='unklar', max_length=20)),
                ('begruendung', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NIS2-Betroffenheits-Check',
                'verbose_name_plural': 'NIS2-Betroffenheits-Checks',
            },
        ),
        migrations.CreateModel(
            name='KontrollAntwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage_id', models.CharField(max_length=40, unique=True)),
                ('titel', models.CharField(max_length=200)),
                ('frage_text', models.TextField()),
                ('reife_stufe', models.IntegerField(choices=[(0, 'Nicht etabliert'), (1, 'Initial / ad-hoc'), (2, 'Geplant / dokumentiert'), (3, 'Umgesetzt / messbar'), (4, 'Optimiert / kontinuierlich verbessert')], default=0)),
                ('nachweis', models.TextField(blank=True, default='', help_text='Verweis auf Doku/Policy, optional. Kein Upload im MVP.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NIS2-Kontroll-Antwort',
                'verbose_name_plural': 'NIS2-Kontroll-Antworten',
                'ordering': ['frage_id'],
            },
        ),
    ]
