# Generated by Django 5.0.14 on 2026-05-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unternehmensstammblatt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_name', models.CharField(max_length=200)),
                ('rechtsform', models.CharField(choices=[('gmbh', 'GmbH'), ('ug', 'UG (haftungsbeschränkt)'), ('ag', 'AG'), ('kg', 'KG / GmbH & Co. KG'), ('ohg', 'OHG'), ('einzel', 'Einzelunternehmen'), ('se', 'Societas Europaea'), ('ev', 'e.V.'), ('sonstiges', 'Sonstiges')], default='gmbh', max_length=20)),
                ('handelsregister_nummer', models.CharField(blank=True, default='', help_text="z. B. 'HRB 123456' (Amtsgericht). Format frei, wird normalisiert.", max_length=40)),
                ('handelsregister_amtsgericht', models.CharField(blank=True, default='', help_text="z. B. 'AG München'.", max_length=100)),
                ('ust_id_nummer', models.CharField(blank=True, default='', help_text="z. B. 'DE123456789'.", max_length=30)),
                ('steuer_nummer', models.CharField(blank=True, default='', max_length=30)),
                ('transparenzregister_id', models.CharField(blank=True, default='', help_text='Eintragungsnummer im Transparenzregister (TR).', max_length=80)),
                ('strasse', models.CharField(blank=True, default='', max_length=200)),
                ('plz', models.CharField(blank=True, default='', max_length=12)),
                ('ort', models.CharField(blank=True, default='', max_length=120)),
                ('land', models.CharField(default='Deutschland', max_length=80)),
                ('gwg_pflicht', models.CharField(choices=[('unbekannt', 'Noch nicht geprüft'), ('nein', 'Nicht GwG-pflichtig'), ('ja', 'GwG-pflichtig')], default='unbekannt', help_text='GwG § 19 Pflicht zur Meldung wirtschaftlich Berechtigter.', max_length=20)),
                ('bundesanzeiger_monitoring_aktiv', models.BooleanField(default=False, help_text='Wöchentliches Polling der Bundesanzeiger-Volltext-API auf Bekanntmachungen zu diesem HRB.')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unternehmensstammblatt',
                'verbose_name_plural': 'Unternehmensstammblätter',
            },
        ),
        migrations.CreateModel(
            name='RegisterBekanntmachung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quelle', models.CharField(default='bundesanzeiger', help_text='bundesanzeiger | transparenzregister', max_length=40)),
                ('titel', models.CharField(max_length=300)),
                ('veroeffentlicht_am', models.DateField()),
                ('url', models.URLField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stammblatt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bekanntmachungen', to='transparenzregister.unternehmensstammblatt')),
            ],
            options={
                'verbose_name': 'Register-Bekanntmachung',
                'verbose_name_plural': 'Register-Bekanntmachungen',
                'ordering': ['-veroeffentlicht_am'],
            },
        ),
        migrations.CreateModel(
            name='WirtschaftlichBerechtigter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('geburtsdatum', models.DateField(blank=True, null=True)),
                ('wohnort_land', models.CharField(default='Deutschland', max_length=80)),
                ('art_des_interesses', models.CharField(blank=True, default='', help_text="z. B. 'Geschäftsanteile 30%', 'Stimmrechte 35%'.", max_length=200)),
                ('anteil_prozent', models.DecimalField(blank=True, decimal_places=2, help_text='Prozentualer Anteil (≥ 25% löst Meldepflicht aus).', max_digits=5, null=True)),
                ('meldung_an_transparenzregister_am', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stammblatt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berechtigte', to='transparenzregister.unternehmensstammblatt')),
            ],
            options={
                'verbose_name': 'Wirtschaftlich Berechtigter',
                'verbose_name_plural': 'Wirtschaftlich Berechtigte',
                'ordering': ['nachname', 'vorname'],
            },
        ),
        migrations.AddConstraint(
            model_name='registerbekanntmachung',
            constraint=models.UniqueConstraint(fields=('stammblatt', 'quelle', 'url'), name='register_unique_bekanntmachung'),
        ),
    ]
