# Generated by Django 5.0.14 on 2026-05-09 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields
import hinschg.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0006_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meldung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "eingangs_token",
                    models.CharField(
                        db_index=True,
                        default=hinschg.models._generate_eingangs_token,
                        editable=False,
                        help_text="256-bit Token. Identifier des Hinweisgebers für Status-Abfrage.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "eingangs_kanal",
                    models.CharField(
                        choices=[
                            ("web_anonym", "Web (anonym)"),
                            ("web_persoenlich", "Web (mit Kontakt)"),
                            ("email", "E-Mail"),
                            ("telefon", "Telefon"),
                            ("persoenlich", "Persönlich"),
                        ],
                        default="web_anonym",
                        max_length=20,
                    ),
                ),
                ("anonym", models.BooleanField(default=True)),
                (
                    "titel_verschluesselt",
                    core.fields.EncryptedTextField(
                        help_text="Kurztitel der Meldung (Klartext). Encryption automatisch."
                    ),
                ),
                (
                    "beschreibung_verschluesselt",
                    core.fields.EncryptedTextField(
                        help_text="Volltext der Meldung. Encryption automatisch."
                    ),
                ),
                (
                    "melder_kontakt_verschluesselt",
                    core.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Optionale Kontakt-Info des Hinweisgebers (nur wenn anonym=False).",
                    ),
                ),
                (
                    "kategorie",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vom Bearbeiter klassifiziert (z. B. 'korruption', 'arbeitssicherheit').",
                        max_length=50,
                    ),
                ),
                (
                    "schweregrad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("niedrig", "Niedrig"),
                            ("mittel", "Mittel"),
                            ("hoch", "Hoch"),
                            ("kritisch", "Kritisch"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("eingegangen", "Eingegangen"),
                            ("bestaetigt", "Eingangsbestätigung versandt"),
                            ("in_pruefung", "In Prüfung"),
                            ("massnahme", "Maßnahme eingeleitet"),
                            ("abgeschlossen", "Abgeschlossen"),
                            ("abgewiesen", "Abgewiesen (kein HinSchG-Verstoß)"),
                        ],
                        default="eingegangen",
                        max_length=30,
                    ),
                ),
                ("eingegangen_am", models.DateTimeField(auto_now_add=True)),
                ("bestaetigung_versandt_am", models.DateTimeField(blank=True, null=True)),
                (
                    "rueckmeldung_faellig_bis",
                    models.DateField(default=hinschg.models._default_rueckmeldung_faellig_bis),
                ),
                ("abgeschlossen_am", models.DateTimeField(blank=True, null=True)),
                (
                    "archiv_loeschdatum",
                    models.DateField(
                        blank=True,
                        help_text="3 Jahre nach Abschluss (HinSchG §11). Auto-Lösch-Job in Phase 2.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "HinSchG-Meldung",
                "verbose_name_plural": "HinSchG-Meldungen",
                "ordering": ["-eingegangen_am"],
                "indexes": [
                    models.Index(
                        fields=["status", "rueckmeldung_faellig_bis"],
                        name="hinschg_mel_status_bde961_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Bearbeitungsschritt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "aktion",
                    models.CharField(
                        help_text="z. B. 'klassifizierung', 'rueckmeldung', 'hinweisgeber_nachricht'.",
                        max_length=50,
                    ),
                ),
                ("notiz_verschluesselt", core.fields.EncryptedTextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "bearbeiter",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = Hinweisgeber-Nachricht (anonym, über Status-API).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hinschg_bearbeitungsschritte",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meldung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bearbeitungsschritte",
                        to="hinschg.meldung",
                    ),
                ),
            ],
            options={
                "verbose_name": "HinSchG-Bearbeitungsschritt",
                "verbose_name_plural": "HinSchG-Bearbeitungsschritte",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MeldungsTask",
            fields=[
                (
                    "compliancetask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.compliancetask",
                    ),
                ),
                (
                    "pflicht_typ",
                    models.CharField(
                        choices=[
                            ("bestaetigung_7d", "Eingangsbestätigung (7 Tage HinSchG §17 Abs. 2)"),
                            ("rueckmeldung_3m", "Rückmeldung (3 Monate HinSchG §17 Abs. 4)"),
                            ("abschluss", "Abschluss-Mitteilung an Hinweisgeber"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "meldung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="hinschg.meldung",
                    ),
                ),
            ],
            options={
                "verbose_name": "HinSchG-Pflicht-Task",
                "verbose_name_plural": "HinSchG-Pflicht-Tasks",
                "unique_together": {("meldung", "pflicht_typ")},
            },
            bases=("core.compliancetask",),
        ),
    ]
