# Generated by Django 5.0.14 on 2026-05-17 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auftragsverarbeitung', '0001_initial'),
        ('core', '0007_llmcalllog'),
        ('datenpannen', '0001_initial'),
        ('ki_inventar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AimsManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durchgefuehrt_am', models.DateField()),
                ('teilnehmer', models.TextField(help_text='Freitext-Liste der Teilnehmer + Rollen.')),
                ('inputs_zusammenfassung', models.TextField(help_text='Incidents, AIIAs, Kennzahlen, externe Änderungen, Audit-Ergebnisse.')),
                ('entscheidungen', models.TextField()),
                ('massnahmen', models.JSONField(blank=True, default=list)),
                ('naechste_review_faellig_am', models.DateField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('freigegeben_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mitarbeiter')),
            ],
            options={
                'verbose_name': 'AIMS Management-Review',
                'verbose_name_plural': 'AIMS Management-Reviews',
                'ordering': ['-durchgefuehrt_am'],
            },
        ),
        migrations.CreateModel(
            name='AiPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geltungsbereich', models.CharField(choices=[('allgemein', 'Allgemeine KI-Policy'), ('akzeptable_nutzung', 'Akzeptable Nutzung (Mitarbeiter)'), ('incident', 'Vorfall-Management-Policy'), ('lifecycle', 'KI-Lifecycle-Policy'), ('drittpartei', 'Drittpartei-KI-Policy')], db_index=True, max_length=40)),
                ('titel', models.CharField(max_length=200)),
                ('inhalt_markdown', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('ratified_at', models.DateField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=False)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nachfolger', to='iso42001.aipolicy')),
                ('ratified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mitarbeiter')),
            ],
            options={
                'verbose_name': 'KI-Policy',
                'verbose_name_plural': 'KI-Policies',
                'ordering': ['geltungsbereich', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AiPolicyKenntnisnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestaetigt_am', models.DateTimeField(auto_now_add=True)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_policy_kenntnisnahmen', to='core.mitarbeiter')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kenntnisnahmen', to='iso42001.aipolicy')),
            ],
            options={
                'verbose_name': 'Policy-Kenntnisnahme',
                'verbose_name_plural': 'Policy-Kenntnisnahmen',
            },
        ),
        migrations.CreateModel(
            name='AiSystemRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risiko_aims', models.CharField(choices=[('niedrig', 'Niedrig'), ('mittel', 'Mittel'), ('hoch', 'Hoch'), ('kritisch', 'Kritisch')], default='mittel', help_text='AIMS-Risiko (≠ AI-Act-Risiko). Treibt AIIA-Pflicht und Kompetenz-Schulungs-Trigger.', max_length=20)),
                ('trainings_daten_quelle', models.TextField(blank=True, default='', help_text='A.7.4/A.7.5 — Herkunft und Lizenzlage der Trainingsdaten.')),
                ('bias_tests_durchgefuehrt', models.BooleanField(default=False)),
                ('bias_tests_dokument_url', models.URLField(blank=True, default='')),
                ('monitoring_plan', models.TextField(blank=True, default='', help_text='A.6.2.6 — Operation-Monitoring.')),
                ('decommissioning_plan', models.TextField(blank=True, default='', help_text='A.6.2.8 — Decommissioning.')),
                ('in_aims_scope', models.BooleanField(default=True, help_text='Wenn False, ist das KI-Tool zwar im KI-Inventar gelistet, aber nicht im AIMS-Geltungsbereich (z. B. Spielwiese).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drittpartei_avv', models.ForeignKey(blank=True, help_text='AVV-Eintrag (Auftragsverarbeiter) für KI-Drittanbieter, falls PII verarbeitet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auftragsverarbeitung.auftragsverarbeiter')),
                ('ki_tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aims_registrierung', to='ki_inventar.kitool')),
                ('verantwortliche_rolle', models.ForeignKey(blank=True, help_text='AI Risk Owner (A.3.2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mitarbeiter')),
            ],
            options={
                'verbose_name': 'AI-System-Registrierung (AIMS)',
                'verbose_name_plural': 'AI-System-Registrierungen (AIMS)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('bias_entdeckt', 'Bias / Diskriminierung entdeckt'), ('output_fehler', 'Fehlerhafter Output / Halluzination mit Schaden'), ('datenleck', 'Datenleck via KI-System'), ('drift', 'Model-Drift / Performance-Verschlechterung'), ('missbrauch', 'Missbräuchliche Nutzung durch User'), ('sonstiges', 'Sonstiges')], max_length=30)),
                ('schweregrad', models.CharField(choices=[('niedrig', 'Niedrig'), ('mittel', 'Mittel'), ('hoch', 'Hoch'), ('kritisch', 'Kritisch (Meldung an Behörde nötig)')], max_length=20)),
                ('entdeckt_am', models.DateField()),
                ('beschreibung', models.TextField()),
                ('sofortmassnahme', models.TextField(blank=True, default='')),
                ('korrekturmassnahme', models.TextField(blank=True, default='')),
                ('abgeschlossen_am', models.DateField(blank=True, null=True)),
                ('gemeldet_an_bnetza', models.BooleanField(default=False)),
                ('bnetza_meldung_datum', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datenpanne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='datenpannen.datenpanne')),
                ('erfasser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ai_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='iso42001.aisystemregistration')),
            ],
            options={
                'verbose_name': 'KI-Vorfall',
                'verbose_name_plural': 'KI-Vorfälle',
                'ordering': ['-entdeckt_am'],
            },
        ),
        migrations.CreateModel(
            name='AiImpactAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('zweck_beschreibung', models.TextField()),
                ('betroffene_personen', models.TextField(help_text='Wer ist Output-betroffen? Mitarbeiter, Kunden, Bewerber, Bürger ...')),
                ('auswirkungs_kategorien', models.JSONField(blank=True, default=list, help_text='Liste der AuswirkungsKategorie-Werte.')),
                ('risiken_identifiziert', models.JSONField(blank=True, default=list, help_text='Liste {risiko, wahrscheinlichkeit, schweregrad}.')),
                ('mitigationen', models.TextField(blank=True, default='')),
                ('restrisiko', models.TextField(blank=True, default='')),
                ('restrisiko_akzeptabel', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('bewertung', 'In Bewertung'), ('approval_offen', 'Wartet auf Freigabe'), ('freigegeben', 'Freigegeben'), ('abgelehnt', 'Abgelehnt'), ('archiviert', 'Archiviert (durch neuere Version ersetzt)')], default='entwurf', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('naechste_review', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, help_text='Wer hat freigegeben? MUSS ≠ erstellt_von sein (4-Augen-Prinzip).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('erstellt_von', models.ForeignKey(blank=True, help_text='Wer hat den Entwurf angelegt? Wird für 4-Augen-Prüfung benötigt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nachfolger', to='iso42001.aiimpactassessment')),
                ('ai_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiias', to='iso42001.aisystemregistration')),
            ],
            options={
                'verbose_name': 'AI Impact Assessment (AIIA)',
                'verbose_name_plural': 'AI Impact Assessments (AIIAs)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_code', models.CharField(db_index=True, max_length=10)),
                ('anwendbar', models.BooleanField(default=True)),
                ('nicht_anwendbar_begruendung', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('geplant', 'Geplant'), ('umgesetzt', 'Umgesetzt'), ('abgeschlossen', 'Abgeschlossen + dokumentiert'), ('nicht_anwendbar', 'Nicht anwendbar (SoA-Ausschluss)')], default='offen', max_length=30)),
                ('beschreibung', models.TextField(blank=True, default='')),
                ('review_datum', models.DateField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verantwortlicher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iso42001_controls', to='core.mitarbeiter')),
            ],
            options={
                'verbose_name': 'ISO 42001 Control-Umsetzung',
                'verbose_name_plural': 'ISO 42001 Control-Umsetzungen',
                'ordering': ['control_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='aipolicykenntnisnahme',
            constraint=models.UniqueConstraint(fields=('policy', 'mitarbeiter'), name='iso42001_policy_kenntnisnahme_unique'),
        ),
        migrations.AddConstraint(
            model_name='controlimplementation',
            constraint=models.UniqueConstraint(fields=('control_code',), name='iso42001_control_impl_unique_code'),
        ),
    ]
