# Generated by Django 5.0.14 on 2026-05-30 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnternehmensProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmenname', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('branche', models.CharField(blank=True, max_length=120)),
                ('nace_code', models.CharField(blank=True, max_length=20)),
                ('mitarbeiter_anzahl', models.IntegerField(default=0)),
                ('jahresumsatz_eur', models.BigIntegerField(default=0)),
                ('rechtsform', models.CharField(blank=True, max_length=60)),
                ('standort_laender', models.JSONField(blank=True, default=list)),
                ('nis2_sektor', models.CharField(blank=True, max_length=30)),
                ('ist_automotive_zulieferer', models.BooleanField(default=False)),
                ('hat_oem_kunden', models.BooleanField(default=False)),
                ('stellt_produkte_her', models.BooleanField(default=False)),
                ('produkte_mit_digitalen_elementen', models.BooleanField(default=False)),
                ('verarbeitet_personenbezogene_daten', models.BooleanField(default=True)),
                ('verarbeitet_gesundheits_sozialdaten', models.BooleanField(default=False)),
                ('setzt_ki_ein', models.BooleanField(default=False)),
                ('betriebsmerkmale', models.JSONField(blank=True, default=list)),
                ('betriebsmerkmale_freitext', models.JSONField(blank=True, default=list)),
                ('recherche_quelle', models.TextField(blank=True)),
                ('recherche_rohdaten', models.JSONField(blank=True, default=dict)),
                ('bestaetigt_at', models.DateTimeField(blank=True, null=True)),
                ('erstellt_at', models.DateTimeField(auto_now_add=True)),
                ('bestaetigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bestaetigte_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegulierungsBefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulierung_code', models.CharField(max_length=40)),
                ('trifft_zu', models.BooleanField(default=True)),
                ('relevanz', models.CharField(max_length=10)),
                ('begruendung', models.TextField()),
                ('abdeckung', models.CharField(max_length=20)),
                ('modul_key', models.CharField(blank=True, max_length=40)),
                ('erstellt_at', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='befunde', to='onboarding_wizard.unternehmensprofil')),
            ],
        ),
        migrations.CreateModel(
            name='OperativeEmpfehlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merkmal_key', models.CharField(max_length=60)),
                ('art', models.CharField(max_length=20)),
                ('ziel', models.CharField(max_length=255)),
                ('quelle', models.CharField(max_length=20)),
                ('rechtsgrundlage', models.CharField(blank=True, max_length=120)),
                ('erstellt_at', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empfehlungen', to='onboarding_wizard.unternehmensprofil')),
            ],
        ),
    ]
