# Generated by Django 5.0.14 on 2026-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_wizard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulierungsbefund',
            name='profil_version',
            field=models.IntegerField(default=1),
        ),
    ]
