# Generated by Django 5.0.14 on 2026-05-17 16:06

import arbeitsschutz.models.gbu
import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_llmcalllog'),
        ('hinschg', '0001_initial'),
        ('pflichtunterweisung', '0008_task_gestartet_am'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsaKonfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_ort', models.CharField(blank=True, default='', max_length=200)),
                ('default_wochentag', models.PositiveSmallIntegerField(default=2, help_text='0=Mo, 6=So. Für Quartals-Auto-Generierung.')),
                ('default_uhrzeit', models.TimeField(default='10:00')),
                ('aktiv', models.BooleanField(default=True, help_text='Ab 21 MA Pflicht. Tenant kann manuell deaktivieren bei <21 MA.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ASA-Konfiguration',
                'verbose_name_plural': 'ASA-Konfigurationen',
            },
        ),
        migrations.CreateModel(
            name='BeauftragtenQuoteCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('sibe', 'Sicherheitsbeauftragter (SGB VII §22)'), ('brandschutz', 'Brandschutzbeauftragter'), ('ersthelfer', 'Ersthelfer'), ('gefahrgut', 'Gefahrgutbeauftragter'), ('laser', 'Laserschutzbeauftragter'), ('strahlenschutz', 'Strahlenschutzbeauftragter'), ('datenschutz', 'Datenschutzbeauftragter (Querverweis)'), ('ki', 'KI-Beauftragter (Querverweis)'), ('sonstiges', 'Sonstiges')], max_length=30, unique=True)),
                ('soll', models.PositiveSmallIntegerField()),
                ('ist', models.PositiveSmallIntegerField()),
                ('pflicht_seit', models.DateField(blank=True, null=True)),
                ('berechnet_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Beauftragten-Quoten-Check',
                'verbose_name_plural': 'Beauftragten-Quoten-Checks',
                'ordering': ['typ'],
            },
        ),
        migrations.CreateModel(
            name='BeauftragterBestellungTask',
            fields=[
                ('compliancetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.compliancetask')),
                ('typ', models.CharField(choices=[('sibe', 'Sicherheitsbeauftragter (SGB VII §22)'), ('brandschutz', 'Brandschutzbeauftragter'), ('ersthelfer', 'Ersthelfer'), ('gefahrgut', 'Gefahrgutbeauftragter'), ('laser', 'Laserschutzbeauftragter'), ('strahlenschutz', 'Strahlenschutzbeauftragter'), ('datenschutz', 'Datenschutzbeauftragter (Querverweis)'), ('ki', 'KI-Beauftragter (Querverweis)'), ('sonstiges', 'Sonstiges')], max_length=30)),
                ('soll', models.PositiveSmallIntegerField(default=1)),
                ('ist', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Beauftragten-Bestellungs-Task',
                'verbose_name_plural': 'Beauftragten-Bestellungs-Tasks',
            },
            bases=('core.compliancetask',),
        ),
        migrations.CreateModel(
            name='Betriebsanweisung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('maschine', 'Maschine/Anlage'), ('gefahrstoff', 'Gefahrstoff'), ('psa', 'Persönliche Schutzausrüstung'), ('taetigkeit', 'Tätigkeit')], max_length=30)),
                ('aushang_pflicht', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Betriebsanweisung',
                'verbose_name_plural': 'Betriebsanweisungen',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='GbuGefaehrdung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freitext_ergaenzung', models.TextField(blank=True, default='', help_text='Tenant-spezifische Erläuterung zur Standard-Gefährdung.')),
                ('wahrscheinlichkeit', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('schwere', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('relevant', models.BooleanField(default=True, help_text='False = im Katalog, hier aber nicht zutreffend (mit Begründung).')),
                ('nicht_relevant_begruendung', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'GBU-Position',
                'verbose_name_plural': 'GBU-Positionen',
            },
        ),
        migrations.CreateModel(
            name='GbuReviewTask',
            fields=[
                ('compliancetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.compliancetask')),
                ('anlass', models.CharField(choices=[('neue_taetigkeit', 'Neue Tätigkeit ohne GBU'), ('wirksamkeit', 'Wirksamkeitsprüfung fällig'), ('nach_unfall', 'Überarbeitung nach Unfall')], max_length=30)),
            ],
            options={
                'verbose_name': 'GBU-Review-Task',
                'verbose_name_plural': 'GBU-Review-Tasks',
            },
            bases=('core.compliancetask',),
        ),
        migrations.CreateModel(
            name='Gefaehrdungsbeurteilung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('in_bewertung', 'In Bewertung'), ('freigegeben', 'Freigegeben'), ('zu_ueberarbeiten', 'Zu überarbeiten')], default='entwurf', max_length=30)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('freigegeben_am', models.DateTimeField(blank=True, null=True)),
                ('wirksamkeitspruefung_faellig_am', models.DateField(default=arbeitsschutz.models.gbu._default_wirksamkeit_faellig, help_text='Default: Freigabe-Datum + 12 Monate (BAuA-Empfehlung).')),
                ('bemerkung', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Gefährdungsbeurteilung',
                'verbose_name_plural': 'Gefährdungsbeurteilungen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='MassnahmenVorschlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorschlaege', models.JSONField(default=list, help_text='[{"titel":"...","beschreibung":"...","stop":"T"}]')),
                ('begruendung', models.TextField(blank=True, default='')),
                ('llm_modell', models.CharField(blank=True, default='', max_length=100)),
                ('llm_prompt_hash', models.CharField(blank=True, default='', max_length=64)),
                ('quelle', models.CharField(default='llm', max_length=20)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('akzeptiert', 'Akzeptiert'), ('verworfen', 'Verworfen')], default='offen', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('entschieden_am', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Maßnahmen-Vorschlag',
                'verbose_name_plural': 'Maßnahmen-Vorschläge',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='MassnahmeTask',
            fields=[
                ('compliancetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.compliancetask')),
            ],
            options={
                'verbose_name': 'Maßnahme-Task',
                'verbose_name_plural': 'Maßnahme-Tasks',
            },
            bases=('core.compliancetask',),
        ),
        migrations.CreateModel(
            name='MitarbeiterTaetigkeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seit', models.DateField()),
                ('bis', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mitarbeiter-Tätigkeit',
                'verbose_name_plural': 'Mitarbeiter-Tätigkeiten',
            },
        ),
        migrations.CreateModel(
            name='Schutzmassnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True, default='')),
                ('hierarchie_stufe', models.CharField(choices=[('S', 'Substitution (Ersetzen)'), ('T', 'Technische Maßnahme'), ('O', 'Organisatorische Maßnahme'), ('P', 'Personenbezogene Maßnahme (PSA)')], max_length=2)),
                ('frist', models.DateField()),
                ('status', models.CharField(choices=[('geplant', 'Geplant'), ('umgesetzt', 'Umgesetzt'), ('wirksam_geprueft', 'Wirksamkeit geprüft'), ('verworfen', 'Verworfen (nicht umsetzbar)')], default='geplant', max_length=20)),
                ('umgesetzt_am', models.DateField(blank=True, null=True)),
                ('wirksamkeitspruefung_am', models.DateField(blank=True, null=True)),
                ('wirksamkeit_kommentar', models.TextField(blank=True, default='')),
                ('wirksam', models.BooleanField(blank=True, help_text='True = Maßnahme wirksam. False = nicht wirksam → Folge-Maßnahme nötig.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schutzmaßnahme',
                'verbose_name_plural': 'Schutzmaßnahmen',
                'ordering': ['hierarchie_stufe', 'frist'],
            },
        ),
        migrations.CreateModel(
            name='Taetigkeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True, default='')),
                ('aktiv', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tätigkeit',
                'verbose_name_plural': 'Tätigkeiten',
                'ordering': ['arbeitsbereich__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnfallMeldungTask',
            fields=[
                ('compliancetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.compliancetask')),
            ],
            options={
                'verbose_name': 'Unfall-Meldung-Task',
                'verbose_name_plural': 'Unfall-Meldung-Tasks',
            },
            bases=('core.compliancetask',),
        ),
        migrations.CreateModel(
            name='Arbeitsbereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('werkstatt', 'Werkstatt'), ('lager', 'Lager'), ('buero', 'Büro'), ('labor', 'Labor'), ('aussen', 'Außenmontage / Baustelle'), ('lieferung', 'Lieferung / Logistik'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=30)),
                ('standort', models.CharField(blank=True, default='', max_length=200)),
                ('beschreibung', models.TextField(blank=True, default='')),
                ('aktiv', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verantwortlicher', models.ForeignKey(blank=True, help_text='Mitarbeiter:in, die für den Bereich operativ verantwortet.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verantwortet_bereiche', to='core.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Arbeitsbereich',
                'verbose_name_plural': 'Arbeitsbereiche',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Arbeitsunfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField()),
                ('schwere', models.CharField(choices=[('bagatell', 'Bagatell (keine AU)'), ('leicht', 'Leicht (AU ≤ 3 Tage)'), ('meldepflichtig', 'Meldepflichtig (AU > 3 Tage)'), ('schwer', 'Schwer'), ('toedlich', 'Tödlich'), ('fast_unfall', 'Beinahe-Unfall')], max_length=30)),
                ('betroffener_name_verschluesselt', core.fields.EncryptedTextField(blank=True, default='', help_text='Klarname falls extern; bei internem MA siehe betroffener_intern.')),
                ('beschreibung_verschluesselt', core.fields.EncryptedTextField(help_text='Hergang. Verschlüsselt at-rest.')),
                ('verletzungsart_verschluesselt', core.fields.EncryptedTextField(blank=True, default='', help_text='Art der Verletzung (Gesundheitsdatum). Verschlüsselt at-rest.')),
                ('ausfalltage', models.PositiveSmallIntegerField(default=0)),
                ('aus_hinschg', models.BooleanField(default=False, help_text='True wenn aus HinSchG-Meldung abgeleitet.')),
                ('bg_meldung_pflicht', models.BooleanField(default=False, help_text='Auto-berechnet aus schwere+ausfalltage.')),
                ('bg_meldefrist', models.DateField(blank=True, help_text='3 Werktage bei meldepflichtig, today bei schwer/toedlich.', null=True)),
                ('bg_gemeldet_am', models.DateField(blank=True, null=True)),
                ('bg_aktenzeichen', models.CharField(blank=True, default='', max_length=80)),
                ('massnahmen_md', models.TextField(blank=True, default='', help_text='Sofort + dauerhaft. Kann zu Schutzmassnahme-Eintraegen verlinken.')),
                ('abgeleitete_gbu_aktualisierung', models.BooleanField(default=False, help_text='True wenn GBU der Tätigkeit nach Unfall aktualisiert wurde.')),
                ('erfasst_am', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arbeitsbereich', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unfaelle', to='arbeitsschutz.arbeitsbereich')),
                ('aus_hinschg_meldung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abgeleitete_unfaelle', to='hinschg.meldung')),
                ('betroffener_intern', models.ForeignKey(blank=True, help_text='Optional — wenn betroffene Person interner MA. Sonst nur Klarname verschluesselt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unfaelle', to='core.mitarbeiter')),
                ('erfasst_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erfasste_unfaelle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arbeitsunfall',
                'verbose_name_plural': 'Arbeitsunfälle',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='AsaSitzung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('geplant_am', models.DateTimeField()),
                ('ort', models.CharField(blank=True, default='', max_length=200)),
                ('tagesordnung_md', models.TextField(blank=True, default='')),
                ('protokoll_md', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('geplant', 'Geplant'), ('durchgefuehrt', 'Durchgeführt'), ('ausgefallen', 'Ausgefallen')], default='geplant', max_length=20)),
                ('durchgefuehrt_am', models.DateTimeField(blank=True, null=True)),
                ('quartal', models.CharField(db_index=True, help_text="Format '2026-Q2' — für Pflicht-Tracking.", max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teilnehmer', models.ManyToManyField(blank=True, related_name='asa_teilnahmen', to='core.mitarbeiter')),
            ],
            options={
                'verbose_name': 'ASA-Sitzung',
                'verbose_name_plural': 'ASA-Sitzungen',
                'ordering': ['geplant_am'],
            },
        ),
        migrations.CreateModel(
            name='AsaBeschluss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschluss_text', models.TextField()),
                ('frist', models.DateField(blank=True, null=True)),
                ('erledigt', models.BooleanField(default=False)),
                ('erledigt_am', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verantwortlicher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asa_beschluesse', to='core.mitarbeiter')),
                ('sitzung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beschluesse', to='arbeitsschutz.asasitzung')),
            ],
            options={
                'verbose_name': 'ASA-Beschluss',
                'verbose_name_plural': 'ASA-Beschlüsse',
                'ordering': ['frist', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AsaSitzungTask',
            fields=[
                ('compliancetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.compliancetask')),
                ('sitzung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='arbeitsschutz.asasitzung')),
            ],
            options={
                'verbose_name': 'ASA-Sitzungs-Task',
                'verbose_name_plural': 'ASA-Sitzungs-Tasks',
            },
            bases=('core.compliancetask',),
        ),
        migrations.CreateModel(
            name='Beauftragter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('sibe', 'Sicherheitsbeauftragter (SGB VII §22)'), ('brandschutz', 'Brandschutzbeauftragter'), ('ersthelfer', 'Ersthelfer'), ('gefahrgut', 'Gefahrgutbeauftragter'), ('laser', 'Laserschutzbeauftragter'), ('strahlenschutz', 'Strahlenschutzbeauftragter'), ('datenschutz', 'Datenschutzbeauftragter (Querverweis)'), ('ki', 'KI-Beauftragter (Querverweis)'), ('sonstiges', 'Sonstiges')], max_length=30)),
                ('bestellt_am', models.DateField()),
                ('bestellt_bis', models.DateField(blank=True, help_text='Leer = unbefristet. Wenn gesetzt, Auto-Reminder 60 Tage vorher.', null=True)),
                ('bestellurkunde_pdf', models.FileField(blank=True, null=True, upload_to='arbeitsschutz/bestellurkunden/')),
                ('bemerkung', models.TextField(blank=True, default='')),
                ('aktiv', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bestellurkunde_evidence', models.ForeignKey(blank=True, help_text='Optional: Evidence-Verweis auf die generierte Bestellurkunde.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bestellurkunden', to='core.evidence')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beauftragten_rollen', to='core.mitarbeiter')),
                ('schulungsnachweis_kurse', models.ManyToManyField(blank=True, help_text='Schulungskurse, die die Person für diese Rolle absolviert hat.', to='pflichtunterweisung.kurs')),
            ],
            options={
                'verbose_name': 'Beauftragte:r',
                'verbose_name_plural': 'Beauftragte',
                'ordering': ['typ', 'person__nachname'],
            },
        ),
        migrations.CreateModel(
            name='BeauftragterAblaufTask',
            fields=[
                ('compliancetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.compliancetask')),
                ('beauftragter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ablauf_tasks', to='arbeitsschutz.beauftragter')),
            ],
            options={
                'verbose_name': 'Beauftragten-Ablauf-Task',
                'verbose_name_plural': 'Beauftragten-Ablauf-Tasks',
            },
            bases=('core.compliancetask',),
        ),
        migrations.CreateModel(
            name='BetriebsanweisungReviewTask',
            fields=[
                ('compliancetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.compliancetask')),
                ('betriebsanweisung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='arbeitsschutz.betriebsanweisung')),
            ],
            options={
                'verbose_name': 'BA-Review-Task',
                'verbose_name_plural': 'BA-Review-Tasks',
            },
            bases=('core.compliancetask',),
        ),
        migrations.CreateModel(
            name='BetriebsanweisungVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('inhalt_md', models.TextField(help_text='Strukturiert nach DGUV-Vorlage: Anwendungsbereich, Gefahren, Schutzmaßnahmen, Verhalten im Notfall, Erste Hilfe, Instandhaltung.')),
                ('pdf_file', models.FileField(blank=True, help_text='WeasyPrint-generiert.', null=True, upload_to='arbeitsschutz/betriebsanweisungen/')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('freigegeben_am', models.DateTimeField(blank=True, null=True)),
                ('aenderungsgrund', models.TextField(blank=True, default='')),
                ('betriebsanweisung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versionen', to='arbeitsschutz.betriebsanweisung')),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_ba_versionen', to=settings.AUTH_USER_MODEL)),
                ('freigegeben_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freigegebene_ba_versionen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BA-Version',
                'verbose_name_plural': 'BA-Versionen',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='betriebsanweisung',
            name='aktuelle_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='arbeitsschutz.betriebsanweisungversion'),
        ),
        migrations.CreateModel(
            name='Aushang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ort', models.CharField(help_text='z.B. "Halle 3, Maschine M-04"', max_length=200)),
                ('ausgehaengt_am', models.DateField()),
                ('abgehaengt_am', models.DateField(blank=True, null=True)),
                ('ausgehaengt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aushaenge', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aushaenge', to='arbeitsschutz.betriebsanweisungversion')),
            ],
            options={
                'verbose_name': 'Aushang',
                'verbose_name_plural': 'Aushänge',
                'ordering': ['-ausgehaengt_am'],
            },
        ),
        migrations.CreateModel(
            name='GbuGefaehrdungVorschlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorgeschlagene_codes', models.JSONField(default=list, help_text='Liste {code, kurz_begruendung}. z.B. [{"code":"MECH-002","b":"..."}]')),
                ('begruendung', models.TextField(blank=True, default='')),
                ('llm_modell', models.CharField(blank=True, default='', max_length=100)),
                ('llm_prompt_hash', models.CharField(blank=True, default='', max_length=64)),
                ('quelle', models.CharField(default='llm', help_text="'llm' oder 'static' (bei Fallback).", max_length=20)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('akzeptiert', 'Akzeptiert'), ('verworfen', 'Verworfen')], default='offen', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('entschieden_am', models.DateTimeField(blank=True, null=True)),
                ('entschieden_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entschiedene_gef_vorschlaege', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GBU-Gefährdungs-Vorschlag',
                'verbose_name_plural': 'GBU-Gefährdungs-Vorschläge',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Gefaehrdung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='z.B. MECH-002 (Standard) oder TENANT-XYZ-007 (Tenant-eigen).', max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('kategorie', models.CharField(choices=[('mechanisch', 'Mechanische Gefährdungen'), ('elektrisch', 'Elektrische Gefährdungen'), ('gefahrstoffe', 'Gefahrstoffe'), ('biologisch', 'Biologische Arbeitsstoffe'), ('brand_explosion', 'Brand- und Explosionsgefährdungen'), ('thermisch', 'Thermische Gefährdungen (Hitze/Kälte)'), ('laerm', 'Lärm'), ('vibration', 'Vibration'), ('strahlung', 'Strahlung (UV, IR, ionisierend)'), ('ergonomie', 'Ergonomie / physische Belastung'), ('psychisch', 'Psychische Belastung'), ('organisatorisch', 'Arbeitsorganisation')], max_length=30)),
                ('beschreibung', models.TextField()),
                ('hinweis_arbeitsbereich', models.CharField(blank=True, default='', help_text="Typischerweise vorkommend in: 'Werkstatt', 'Außenmontage' etc.", max_length=200)),
                ('rechtsgrundlage', models.CharField(blank=True, default='', help_text="z.B. 'DGUV V1 §4 Abs. 1' oder 'BetrSichV §3'.", max_length=200)),
                ('eigentuemer_tenant', models.CharField(blank=True, default='', help_text='Schema-Name des Tenants, der die Gefährdung angelegt hat. Leer = Vaeren-Standardkatalog (read-only).', max_length=63)),
                ('aktiv', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gefährdung',
                'verbose_name_plural': 'Gefährdungen (Katalog)',
                'ordering': ['kategorie', 'code'],
                'indexes': [models.Index(fields=['kategorie', 'aktiv'], name='arbeitsschu_kategor_41c84f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='gefaehrdung',
            constraint=models.UniqueConstraint(fields=('code', 'eigentuemer_tenant'), name='gefaehrdung_unique_code_per_owner'),
        ),
        migrations.AddField(
            model_name='gbugefaehrdung',
            name='gefaehrdung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arbeitsschutz.gefaehrdung'),
        ),
        migrations.AddField(
            model_name='gefaehrdungsbeurteilung',
            name='erstellt_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_gbus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gefaehrdungsbeurteilung',
            name='freigegeben_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freigegebene_gbus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gefaehrdungsbeurteilung',
            name='verantwortlicher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verantwortete_gbus', to='core.mitarbeiter'),
        ),
        migrations.AddField(
            model_name='gbureviewtask',
            name='gbu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to='arbeitsschutz.gefaehrdungsbeurteilung'),
        ),
        migrations.AddField(
            model_name='gbugefaehrdungvorschlag',
            name='gbu',
            field=models.ForeignKey(blank=True, help_text='Optional, wenn Vorschlag im Kontext einer konkreten GBU entstand.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vorschlaege', to='arbeitsschutz.gefaehrdungsbeurteilung'),
        ),
        migrations.AddField(
            model_name='gbugefaehrdung',
            name='gbu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='arbeitsschutz.gefaehrdungsbeurteilung'),
        ),
        migrations.AddField(
            model_name='massnahmenvorschlag',
            name='entschieden_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='massnahmenvorschlag',
            name='gbu_gefaehrdung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massnahmen_vorschlaege', to='arbeitsschutz.gbugefaehrdung'),
        ),
        migrations.AddField(
            model_name='mitarbeitertaetigkeit',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taetigkeits_zuordnungen', to='core.mitarbeiter'),
        ),
        migrations.AddField(
            model_name='schutzmassnahme',
            name='erstellt_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_schutzmassnahmen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schutzmassnahme',
            name='gbu_gefaehrdungen',
            field=models.ManyToManyField(related_name='massnahmen', to='arbeitsschutz.gbugefaehrdung'),
        ),
        migrations.AddField(
            model_name='schutzmassnahme',
            name='verantwortlicher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schutzmassnahmen', to='core.mitarbeiter'),
        ),
        migrations.AddField(
            model_name='massnahmetask',
            name='massnahme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='arbeitsschutz.schutzmassnahme'),
        ),
        migrations.AddField(
            model_name='taetigkeit',
            name='arbeitsbereich',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taetigkeiten', to='arbeitsschutz.arbeitsbereich'),
        ),
        migrations.AddField(
            model_name='taetigkeit',
            name='benoetigt_kurse',
            field=models.ManyToManyField(blank=True, help_text='Welche Pflichtunterweisungen müssen Mitarbeiter:innen dieser Tätigkeit haben? Bei MA-Zuordnung triggert Bridge ggf. DRAFT-Welle.', related_name='pflicht_fuer_taetigkeiten', to='pflichtunterweisung.kurs'),
        ),
        migrations.AddField(
            model_name='taetigkeit',
            name='verantwortlicher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verantwortet_taetigkeiten', to='core.mitarbeiter'),
        ),
        migrations.AddField(
            model_name='mitarbeitertaetigkeit',
            name='taetigkeit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitarbeiter_zuordnungen', to='arbeitsschutz.taetigkeit'),
        ),
        migrations.AddField(
            model_name='gefaehrdungsbeurteilung',
            name='taetigkeit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gbus', to='arbeitsschutz.taetigkeit'),
        ),
        migrations.AddField(
            model_name='gbureviewtask',
            name='taetigkeit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='arbeitsschutz.taetigkeit'),
        ),
        migrations.AddField(
            model_name='gbugefaehrdungvorschlag',
            name='taetigkeit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gefaehrdungs_vorschlaege', to='arbeitsschutz.taetigkeit'),
        ),
        migrations.AddField(
            model_name='betriebsanweisung',
            name='taetigkeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betriebsanweisungen', to='arbeitsschutz.taetigkeit'),
        ),
        migrations.AddField(
            model_name='arbeitsunfall',
            name='taetigkeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unfaelle', to='arbeitsschutz.taetigkeit'),
        ),
        migrations.AddField(
            model_name='unfallmeldungtask',
            name='unfall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='arbeitsschutz.arbeitsunfall'),
        ),
        migrations.AddConstraint(
            model_name='asasitzung',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'geplant')), fields=('quartal',), name='asa_one_geplant_pro_quartal'),
        ),
        migrations.AddIndex(
            model_name='beauftragter',
            index=models.Index(fields=['typ', 'aktiv'], name='arbeitsschu_typ_833f67_idx'),
        ),
        migrations.AddIndex(
            model_name='beauftragter',
            index=models.Index(fields=['bestellt_bis'], name='arbeitsschu_bestell_eb8de4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='betriebsanweisungversion',
            unique_together={('betriebsanweisung', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='gbugefaehrdung',
            unique_together={('gbu', 'gefaehrdung')},
        ),
        migrations.AddIndex(
            model_name='schutzmassnahme',
            index=models.Index(fields=['status', 'frist'], name='arbeitsschu_status_64b532_idx'),
        ),
        migrations.AddIndex(
            model_name='schutzmassnahme',
            index=models.Index(fields=['hierarchie_stufe'], name='arbeitsschu_hierarc_0f6232_idx'),
        ),
        migrations.AddConstraint(
            model_name='taetigkeit',
            constraint=models.UniqueConstraint(fields=('arbeitsbereich', 'name'), name='taetigkeit_unique_in_bereich'),
        ),
        migrations.AlterUniqueTogether(
            name='mitarbeitertaetigkeit',
            unique_together={('mitarbeiter', 'taetigkeit', 'seit')},
        ),
        migrations.AddIndex(
            model_name='gefaehrdungsbeurteilung',
            index=models.Index(fields=['taetigkeit', 'status'], name='arbeitsschu_taetigk_aaf68e_idx'),
        ),
        migrations.AddIndex(
            model_name='gefaehrdungsbeurteilung',
            index=models.Index(fields=['wirksamkeitspruefung_faellig_am'], name='arbeitsschu_wirksam_308c29_idx'),
        ),
        migrations.AddIndex(
            model_name='arbeitsunfall',
            index=models.Index(fields=['schwere', '-datum'], name='arbeitsschu_schwere_c79742_idx'),
        ),
        migrations.AddIndex(
            model_name='arbeitsunfall',
            index=models.Index(fields=['bg_meldung_pflicht', 'bg_gemeldet_am'], name='arbeitsschu_bg_meld_885a33_idx'),
        ),
    ]
