# Generated by Django 5.0.14 on 2026-05-16 13:21

import django.db.models.deletion
import redaktion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quell_url', models.URLField(max_length=500)),
                ('quell_url_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('titel_raw', models.TextField()),
                ('excerpt_raw', models.TextField(blank=True, default='')),
                ('published_at_source', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
                ('curator_begruendung', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'News-Kandidat',
                'verbose_name_plural': 'News-Kandidaten',
                'ordering': ('-fetched_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.URLField()),
                ('parser_key', models.CharField(help_text='FQDN der Parser-Klasse, z.B. redaktion.sources.eur_lex.EurLexParser', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News-Quelle',
                'verbose_name_plural': 'News-Quellen',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RedaktionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('crawler_items_in', models.IntegerField(default=0)),
                ('curator_items_out', models.IntegerField(default=0)),
                ('writer_runs', models.IntegerField(default=0)),
                ('verifier_runs', models.IntegerField(default=0)),
                ('published', models.IntegerField(default=0)),
                ('held', models.IntegerField(default=0)),
                ('cost_eur', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Redaktions-Lauf',
                'verbose_name_plural': 'Redaktions-Läufe',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('titel', models.CharField(max_length=200)),
                ('lead', models.TextField()),
                ('body_html', models.TextField()),
                ('kategorie', models.CharField(choices=[('ai_act', 'AI Act'), ('datenschutz', 'Datenschutz'), ('hinschg', 'HinSchG'), ('lieferkette', 'Lieferkette'), ('arbeitsrecht', 'Arbeitsrecht'), ('geldwaesche_finanzen', 'Geldwäsche/Finanzen'), ('it_sicherheit', 'IT-Sicherheit'), ('esg_nachhaltigkeit', 'ESG/Nachhaltigkeit')], max_length=30)),
                ('geo', models.CharField(choices=[('EU', 'EU'), ('DE', 'DE'), ('EU_DE', 'EU→DE-Umsetzung')], max_length=10)),
                ('type', models.CharField(choices=[('gesetzgebung', 'Gesetzgebung'), ('urteil', 'Urteil'), ('leitlinie', 'Leitlinie/FAQ'), ('konsultation', 'Konsultation'), ('frist', 'Frist')], max_length=20)),
                ('relevanz', models.CharField(choices=[('hoch', 'Hoch'), ('mittel', 'Mittel'), ('niedrig', 'Niedrig')], max_length=10)),
                ('source_links', models.JSONField(default=list, help_text='Liste [{titel: str, url: str}]')),
                ('status', models.CharField(choices=[('pending_verify', 'Wartet auf Verifier'), ('hold', 'Manuelle Sichtung erforderlich'), ('published', 'Live'), ('unpublished', 'Zurückgezogen')], default='pending_verify', max_length=20)),
                ('verifier_confidence', models.FloatField(blank=True, null=True)),
                ('verifier_issues', models.JSONField(blank=True, default=list)),
                ('pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('unpublish_token', models.CharField(default=redaktion.models._generate_unpublish_token, editable=False, max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post', to='redaktion.newscandidate')),
            ],
            options={
                'verbose_name': 'News-Beitrag',
                'verbose_name_plural': 'News-Beiträge',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Korrektur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korrigiert_am', models.DateTimeField(auto_now_add=True)),
                ('was_geaendert', models.TextField()),
                ('grund', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='korrekturen', to='redaktion.newspost')),
            ],
            options={
                'verbose_name': 'Korrektur',
                'verbose_name_plural': 'Korrekturen',
                'ordering': ('-korrigiert_am',),
            },
        ),
        migrations.AddField(
            model_name='newscandidate',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='redaktion.newssource'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['status', 'published_at'], name='redaktion_n_status_3461cb_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['kategorie'], name='redaktion_n_kategor_962932_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['geo'], name='redaktion_n_geo_8d852f_idx'),
        ),
        migrations.AddIndex(
            model_name='newscandidate',
            index=models.Index(fields=['selected_at'], name='redaktion_n_selecte_1cc500_idx'),
        ),
        migrations.AddIndex(
            model_name='newscandidate',
            index=models.Index(fields=['discarded_at'], name='redaktion_n_discard_698230_idx'),
        ),
    ]
