# Generated by Django 5.0.14 on 2026-05-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_llmcalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='KITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('anbieter', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, default='')),
                ('kategorie', models.CharField(choices=[('llm_chatbot', 'LLM/Chatbot'), ('bild_generierung', 'Bild-Generierung'), ('ocr_text', 'OCR / Text-Erkennung'), ('klassifizierung', 'Klassifizierung / Predictive Analytics'), ('empfehlung', 'Empfehlung / Recommender'), ('biometrie', 'Biometrische Erkennung'), ('hr_recruiting', 'HR / Recruiting (Anhang III)'), ('kredit_scoring', 'Kredit-Scoring (Anhang III)'), ('produktion', 'Produktions-/Maschinen-Steuerung'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=40)),
                ('zweck', models.TextField(help_text='Wofür wird das Tool eingesetzt? Konkret, keine Marketing-Sätze.')),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv im Einsatz'), ('pilot', 'Pilot/Test'), ('evaluation', 'In Evaluation'), ('stillgelegt', 'Stillgelegt')], default='evaluation', max_length=20)),
                ('eingefuehrt_am', models.DateField(blank=True, null=True)),
                ('nutzer_anzahl', models.PositiveIntegerField(blank=True, help_text='Anzahl Nutzer:innen im Unternehmen.', null=True)),
                ('datenkategorie_sensibilitaet', models.CharField(choices=[('keine_personendaten', 'Keine Personendaten'), ('gewoehnlich', 'Gewöhnliche Personendaten'), ('besondere_kategorie', 'Besondere Kategorien (Art. 9 DSGVO)')], default='keine_personendaten', max_length=30)),
                ('datenkategorien', models.JSONField(blank=True, default=list, help_text="Liste Datenkategorien (z. B. ['kontaktdaten','gesundheitsdaten']).")),
                ('risiko', models.CharField(choices=[('unbekannt', 'Unbekannt (noch zu klassifizieren)'), ('minimal', 'Minimales Risiko'), ('begrenzt', 'Begrenztes Risiko (Transparenzpflicht)'), ('hoch', 'Hochrisiko (Anhang III)'), ('unakzeptabel', 'Unakzeptables Risiko (verboten)')], default='unbekannt', max_length=20)),
                ('risiko_vorschlag', models.CharField(blank=True, choices=[('unbekannt', 'Unbekannt (noch zu klassifizieren)'), ('minimal', 'Minimales Risiko'), ('begrenzt', 'Begrenztes Risiko (Transparenzpflicht)'), ('hoch', 'Hochrisiko (Anhang III)'), ('unakzeptabel', 'Unakzeptables Risiko (verboten)')], default='', max_length=20)),
                ('risiko_begruendung', models.TextField(blank=True, default='', help_text='Begründung der finalen Einstufung.')),
                ('avv_link', models.URLField(blank=True, default='', help_text='Link zur Auftragsverarbeitungs-Vereinbarung (DPA).')),
                ('konformitaet_link', models.URLField(blank=True, default='', help_text='Link zur Konformitätserklärung des Anbieters (Hochrisiko).')),
                ('dpia_link', models.URLField(blank=True, default='', help_text='Link zur Datenschutz-Folgenabschätzung (DSFA/DPIA).')),
                ('transparenz_information', models.BooleanField(default=False, help_text='Wurde Personal informiert, dass KI eingesetzt wird? (Art. 26 Abs. 7)')),
                ('menschliche_aufsicht', models.BooleanField(default=False, help_text='Ist menschliche Aufsicht/Override-Möglichkeit gewährleistet? (Art. 14)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KI-Tool',
                'verbose_name_plural': 'KI-Tools',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'risiko'], name='ki_inventar_status_239645_idx'), models.Index(fields=['kategorie'], name='ki_inventar_kategor_f1748c_idx')],
            },
        ),
        migrations.CreateModel(
            name='KIToolTask',
            fields=[
                ('compliancetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.compliancetask')),
                ('task_typ', models.CharField(choices=[('klassifizierung', 'Risiko-Klassifizierung abschließen'), ('dpia', 'Datenschutz-Folgenabschätzung (DPIA)'), ('konformitaet', 'Konformitäts-Doku einholen'), ('transparenz', 'Transparenz-Maßnahme umsetzen'), ('stilllegung', 'Stilllegung (unakzeptabel)')], max_length=40)),
                ('ki_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ki_inventar.kitool')),
            ],
            options={
                'verbose_name': 'KI-Tool-Task',
                'verbose_name_plural': 'KI-Tool-Tasks',
            },
            bases=('core.compliancetask',),
        ),
    ]
