# Generated by Django 5.0.14 on 2026-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mitarbeiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("vorname", models.CharField(max_length=100)),
                ("nachname", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("abteilung", models.CharField(max_length=100)),
                ("rolle", models.CharField(help_text="Tätigkeit/Position", max_length=100)),
                ("eintritt", models.DateField()),
                ("austritt", models.DateField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, default="", help_text="ERP-Sync-ID (Phase 2)", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nachname", "vorname"],
            },
        ),
        migrations.AddConstraint(
            model_name="mitarbeiter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__gt", "")),
                fields=("external_id",),
                name="mitarbeiter_unique_external_id_when_set",
            ),
        ),
    ]
