# Generated by Django 5.0.14 on 2026-05-08 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_mitarbeiter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                (
                    "modul",
                    models.CharField(
                        help_text="Modul-Identifier (z. B. 'pflichtunterweisung', 'hinschg')",
                        max_length=50,
                    ),
                ),
                ("kategorie", models.CharField(max_length=50)),
                ("frist", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("in_bearbeitung", "In Bearbeitung"),
                            ("erledigt", "Erledigt"),
                            ("ueberfaellig", "Überfällig"),
                        ],
                        default="offen",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "betroffene",
                    models.ManyToManyField(
                        blank=True, related_name="compliance_tasks", to="core.mitarbeiter"
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "verantwortlicher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_tasks_responsible",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["frist", "titel"],
                "indexes": [
                    models.Index(fields=["status", "frist"], name="core_compli_status_28180d_idx"),
                    models.Index(
                        fields=["modul", "kategorie"], name="core_compli_modul_81bebc_idx"
                    ),
                ],
            },
        ),
    ]
