# Generated by Django 5.0.14 on 2026-05-08 22:23

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_compliancetask"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("datei_path", models.CharField(blank=True, default="", max_length=512)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("mime_type", models.CharField(max_length=100)),
                ("groesse_bytes", models.PositiveBigIntegerField()),
                (
                    "aufbewahrung_bis",
                    models.DateField(default=core.models._default_aufbewahrung_bis),
                ),
                ("immutable", models.BooleanField(default=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bezug_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidences",
                        to="core.compliancetask",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
