# Generated by Django 5.0.14 on 2026-05-08 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_evidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "E-Mail"), ("in_app", "In-App"), ("sms", "SMS")],
                        max_length=20,
                    ),
                ),
                ("template", models.CharField(max_length=100)),
                ("template_kontext", models.JSONField(default=dict)),
                ("geplant_fuer", models.DateTimeField(blank=True, null=True)),
                ("versandt_am", models.DateTimeField(blank=True, null=True)),
                ("geoeffnet_am", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("geplant", "Geplant"),
                            ("versandt", "Versandt"),
                            ("geoeffnet", "Geöffnet"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                        ],
                        default="geplant",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empfaenger_mitarbeiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.mitarbeiter",
                    ),
                ),
                (
                    "empfaenger_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "geplant_fuer"], name="core_notifi_status_e31655_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("empfaenger_mitarbeiter__isnull", True), ("empfaenger_user__isnull", False)
                    ),
                    models.Q(
                        ("empfaenger_mitarbeiter__isnull", False), ("empfaenger_user__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="notification_exactly_one_recipient",
            ),
        ),
    ]
