# Generated by Django 5.0.14 on 2026-05-08 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0005_notification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_email_snapshot", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "aktion",
                    models.CharField(
                        choices=[
                            ("create", "Erstellt"),
                            ("update", "Aktualisiert"),
                            ("delete", "Gelöscht"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("export", "Exportiert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("aenderung_diff", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs_as_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-timestamp"], name="core_auditl_actor_i_cba5aa_idx"
                    ),
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="core_auditl_target__d09aa2_idx",
                    ),
                ],
            },
        ),
    ]
