# Generated by Django 5.0.14 on 2026-05-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modul', models.CharField(help_text="Welches Vaeren-Modul hat den Call ausgelöst (z. B. 'datenpannen').", max_length=50)),
                ('zweck', models.CharField(blank=True, default='', help_text="Konkreter Zweck: 'risiko_vorschlag', 'kursinhalt_generieren', ...", max_length=80)),
                ('modell', models.CharField(max_length=120)),
                ('prompt_hash', models.CharField(blank=True, default='', help_text='SHA-256 des Prompts — auditierbar, ohne Inhalt zu persistieren.', max_length=64)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('kosten_eur', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latenz_ms', models.PositiveIntegerField(default=0)),
                ('erfolgreich', models.BooleanField(default=True)),
                ('fehler', models.TextField(blank=True, default='')),
                ('quelle', models.CharField(default='llm', help_text="'llm' bei echtem Call, 'static' bei Template-Fallback.", max_length=20)),
            ],
            options={
                'verbose_name': 'LLM-Call-Log',
                'verbose_name_plural': 'LLM-Call-Logs',
                'ordering': ['-erstellt_am'],
                'indexes': [models.Index(fields=['modul', '-erstellt_am'], name='core_llmcal_modul_f132ed_idx'), models.Index(fields=['erstellt_am', 'modell'], name='core_llmcal_erstell_b62e12_idx')],
            },
        ),
    ]
